export function loadLists() {
  return [
    {
       "id": "3",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "1672",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "4 andar",
       "cep": "41820020",
       "rbase": "3",
       "nome": "NUTRICASH CREDENCIADO",
       "latitude": -12.977854,
       "longitude": -38.460552,
       "status": "E"
    },
    {
       "id": "9",
       "tipo_logradouro": "Rua",
       "logradouro": "Deputado Paulo Jackson",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Piatã",
       "complemento": "",
       "cep": "41.650-020",
       "rbase": "9",
       "nome": "RAPA NUI",
       "latitude": -12.948005,
       "longitude": -38.383902,
       "status": "E"
    },
    {
       "id": "11",
       "tipo_logradouro": "Avenida",
       "logradouro": "Paulo VI",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "",
       "cep": "41.810-001",
       "rbase": "11",
       "nome": "MIX CALIFORNIA",
       "latitude": -12.993305,
       "longitude": -38.4573902,
       "status": "E"
    },
    {
       "id": "12",
       "tipo_logradouro": "Avenida",
       "logradouro": "Vale do Ogunjá",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Acupe de Brotas",
       "complemento": "",
       "cep": "40.290-110",
       "rbase": "12",
       "nome": "EBAL",
       "latitude": -12.9937824,
       "longitude": -38.4922195,
       "status": "E"
    },
    {
       "id": "13",
       "tipo_logradouro": "Rua",
       "logradouro": "Teotônio Vilela",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Fazenda Coutos",
       "complemento": "",
       "cep": "40730-730",
       "rbase": "13",
       "nome": "MERCADINHO FREITAS",
       "latitude": -12.848228,
       "longitude": -38.464941,
       "status": "E"
    },
    {
       "id": "17",
       "tipo_logradouro": "Rótula",
       "logradouro": "do Abacaxi",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cidade Nova",
       "complemento": "",
       "cep": "40.315-340",
       "rbase": "17",
       "nome": "EXTRA SUPERMERCADO",
       "latitude": -12.989699,
       "longitude": -38.471288,
       "status": "E"
    },
    {
       "id": "18",
       "tipo_logradouro": "Avenida",
       "logradouro": "Luís Viana",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Imbuí",
       "complemento": "",
       "cep": "41.720-200",
       "rbase": "18",
       "nome": "EXTRA SUPERMERCADO",
       "latitude": -12.947721,
       "longitude": -38.423552,
       "status": "E"
    },
    {
       "id": "20",
       "tipo_logradouro": "Rua",
       "logradouro": "Quintino de Carvalho",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Jardim Apipema",
       "complemento": "",
       "cep": "40155-280",
       "rbase": "20",
       "nome": "APIPAO",
       "latitude": -13.003997,
       "longitude": -38.517446,
       "status": "E"
    },
    {
       "id": "22",
       "tipo_logradouro": "Rua",
       "logradouro": "B",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "IAPI",
       "complemento": "",
       "cep": "40.330-470",
       "rbase": "22",
       "nome": "EBAL",
       "latitude": -12.9572075,
       "longitude": -38.4805789,
       "status": "E"
    },
    {
       "id": "23",
       "tipo_logradouro": "Avenida",
       "logradouro": "Estados Unidos",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40.010-020",
       "rbase": "23",
       "nome": "EBAL",
       "latitude": -12.967447,
       "longitude": -38.509558,
       "status": "E"
    },
    {
       "id": "24",
       "tipo_logradouro": "Rua",
       "logradouro": "Mello Moraes Filho",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Fazenda Grande do Retiro",
       "complemento": "",
       "cep": "40.352-000",
       "rbase": "24",
       "nome": "EBAL",
       "latitude": -12.9397086,
       "longitude": -38.47842139999999,
       "status": "E"
    },
    {
       "id": "25",
       "tipo_logradouro": "Rua",
       "logradouro": "Gonçalo Coelho",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Liberdade",
       "complemento": "",
       "cep": "40.325-570",
       "rbase": "25",
       "nome": "EBAL",
       "latitude": -12.9497972,
       "longitude": -38.4930988,
       "status": "E"
    },
    {
       "id": "26",
       "tipo_logradouro": "Avenida",
       "logradouro": "Edgar Santos",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Saboeiro",
       "complemento": "",
       "cep": "41180-790",
       "rbase": "26",
       "nome": "EBAL",
       "latitude": -12.960482,
       "longitude": -38.43937,
       "status": "E"
    },
    {
       "id": "27",
       "tipo_logradouro": "3ª Travessa",
       "logradouro": "24 de Agosto",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pirajá",
       "complemento": "",
       "cep": "41.291-150",
       "rbase": "27",
       "nome": "EBAL",
       "latitude": -12.8967143,
       "longitude": -38.4666834,
       "status": "E"
    },
    {
       "id": "28",
       "tipo_logradouro": "Estrada",
       "logradouro": "do Cabrito",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "São João do Cabrito",
       "complemento": "",
       "cep": "40.490-182",
       "rbase": "28",
       "nome": "EBAL",
       "latitude": -12.9046214,
       "longitude": -38.4750823,
       "status": "E"
    },
    {
       "id": "29",
       "tipo_logradouro": "Praça",
       "logradouro": "General Justo",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Ribeira",
       "complemento": "",
       "cep": "40.420-270",
       "rbase": "29",
       "nome": "EBAL",
       "latitude": -12.9151287,
       "longitude": -38.4968182,
       "status": "E"
    },
    {
       "id": "30",
       "tipo_logradouro": "Avenida",
       "logradouro": "Jequitaia",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Água de Meninos",
       "complemento": "",
       "cep": "40.460-120",
       "rbase": "30",
       "nome": "EBAL",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "31",
       "tipo_logradouro": "Rua",
       "logradouro": "Seis de Janeiro",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Uruguai",
       "complemento": "",
       "cep": "40.450-260",
       "rbase": "31",
       "nome": "EBAL",
       "latitude": -12.933345,
       "longitude": -38.495447,
       "status": "E"
    },
    {
       "id": "63",
       "tipo_logradouro": "1ª Travessa",
       "logradouro": "Januário",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Águas Claras",
       "complemento": "",
       "cep": "41310-380",
       "rbase": "63",
       "nome": "EBAL",
       "latitude": -12.893215,
       "longitude": -38.439511,
       "status": "E"
    },
    {
       "id": "64",
       "tipo_logradouro": "Conjunto",
       "logradouro": "Fazenda Grande I",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cajazeiras",
       "complemento": "",
       "cep": "41340-100",
       "rbase": "64",
       "nome": "EBAL",
       "latitude": -12.9067131,
       "longitude": -38.3965972,
       "status": "E"
    },
    {
       "id": "66",
       "tipo_logradouro": "Rua",
       "logradouro": "Bem-te-vi",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Canabrava",
       "complemento": "",
       "cep": "41260-340",
       "rbase": "66",
       "nome": "EBAL",
       "latitude": -12.924738,
       "longitude": -38.418871,
       "status": "E"
    },
    {
       "id": "69",
       "tipo_logradouro": "Travessa",
       "logradouro": "Genebaldo Figueiredo",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Itapuã",
       "complemento": "",
       "cep": "41610-420",
       "rbase": "69",
       "nome": "EBAL",
       "latitude": -12.950007,
       "longitude": -38.368341,
       "status": "E"
    },
    {
       "id": "71",
       "tipo_logradouro": "Conjunto",
       "logradouro": "Mussurunga I",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Mussurunga I",
       "complemento": "",
       "cep": "41490-060",
       "rbase": "71",
       "nome": "EBAL",
       "latitude": -12.9102878,
       "longitude": -38.3666166,
       "status": "E"
    },
    {
       "id": "74",
       "tipo_logradouro": "Rua",
       "logradouro": "da Matriz",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Valéria",
       "complemento": "",
       "cep": "41.300-600",
       "rbase": "74",
       "nome": "EBAL",
       "latitude": -12.8641778,
       "longitude": -38.4310783,
       "status": "E"
    },
    {
       "id": "75",
       "tipo_logradouro": "Rua",
       "logradouro": "Santa Luzia",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Periperi",
       "complemento": "",
       "cep": "40725-850",
       "rbase": "75",
       "nome": "EBAL",
       "latitude": -12.934676,
       "longitude": -38.434087,
       "status": "E"
    },
    {
       "id": "77",
       "tipo_logradouro": "Conjunto",
       "logradouro": "Cajazeiras VIII",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cajazeiras",
       "complemento": "CASA 02",
       "cep": "41.330-020",
       "rbase": "77",
       "nome": "BETOPAO",
       "latitude": -12.9035317,
       "longitude": -38.4126767,
       "status": "E"
    },
    {
       "id": "87",
       "tipo_logradouro": "Rua",
       "logradouro": "Marquês de Maricá",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pau Miúdo",
       "complemento": "",
       "cep": "40310-000",
       "rbase": "87",
       "nome": "PAN E LAN ELETRICA CRISTAL",
       "latitude": -12.959612,
       "longitude": -38.485924,
       "status": "E"
    },
    {
       "id": "88",
       "tipo_logradouro": "1ª Travessa",
       "logradouro": "do Gama",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho de Areia",
       "complemento": "",
       "cep": "40.440-480",
       "rbase": "88",
       "nome": "HIPER FRANGO",
       "latitude": -12.9301203,
       "longitude": -38.5041053,
       "status": "E"
    },
    {
       "id": "89",
       "tipo_logradouro": "Rua",
       "logradouro": "da Grécia",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40.010-010",
       "rbase": "89",
       "nome": "MERCADO DO COMERCIO",
       "latitude": -12.914238,
       "longitude": -38.439272,
       "status": "E"
    },
    {
       "id": "90",
       "tipo_logradouro": "Avenida",
       "logradouro": "Dom João VI",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Brotas",
       "complemento": "",
       "cep": "40285-001",
       "rbase": "90",
       "nome": "PADARIA  SANTA MARIA",
       "latitude": -12.988594,
       "longitude": -38.481468,
       "status": "E"
    },
    {
       "id": "91",
       "tipo_logradouro": "Rua",
       "logradouro": "Madalena Paraguassu",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pau Miúdo",
       "complemento": "Nº 122",
       "cep": "40.315-360",
       "rbase": "91",
       "nome": "MERCADINHO CRUZEIRO",
       "latitude": -12.964705,
       "longitude": -38.48131,
       "status": "E"
    },
    {
       "id": "92",
       "tipo_logradouro": "Avenida",
       "logradouro": "Santiago de Compostela",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Parque Bela Vista",
       "complemento": "425",
       "cep": "40.279-150",
       "rbase": "92",
       "nome": "ATAKADAO ATAKAREJO",
       "latitude": -12.98197,
       "longitude": -38.471608,
       "status": "E"
    },
    {
       "id": "93",
       "tipo_logradouro": "Avenida",
       "logradouro": "Leovigildo Filgueiras",
       "numero": "304",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Garcia",
       "complemento": "",
       "cep": "40.100-000",
       "rbase": "93",
       "nome": "GARCIA DELICATESSEN",
       "latitude": -12.991398,
       "longitude": -38.518127,
       "status": "E"
    },
    {
       "id": "97",
       "tipo_logradouro": "Avenida",
       "logradouro": "Joana Angélica",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Nazaré",
       "complemento": "N 67",
       "cep": "40.050-001",
       "rbase": "97",
       "nome": "PANIFICADORA JOANA ANGELICA",
       "latitude": -12.982431,
       "longitude": -38.514357,
       "status": "E"
    },
    {
       "id": "99",
       "tipo_logradouro": "Praça",
       "logradouro": "Engenheiro Roberto Pugas",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Itapuã",
       "complemento": "N 01",
       "cep": "41.620-490",
       "rbase": "99",
       "nome": "PANIFICADORA ITAPOA",
       "latitude": -12.9398069,
       "longitude": -38.36793309999999,
       "status": "E"
    },
    {
       "id": "103",
       "tipo_logradouro": "Rua",
       "logradouro": "Raul Leite",
       "numero": "116",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Vila Laura",
       "complemento": "",
       "cep": "40270-010",
       "rbase": "103",
       "nome": "PANILHA SUPER",
       "latitude": -12.972147,
       "longitude": -38.48848,
       "status": "E"
    },
    {
       "id": "104",
       "tipo_logradouro": "Rua",
       "logradouro": "Cosme de Farias",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cosme de Farias",
       "complemento": "N 187",
       "cep": "40.252-000",
       "rbase": "104",
       "nome": "PANDELLI DELICATESSEM",
       "latitude": -12.9802934,
       "longitude": -38.4913883,
       "status": "E"
    },
    {
       "id": "105",
       "tipo_logradouro": "Rua",
       "logradouro": "do Norte",
       "numero": "1203",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Nordeste",
       "complemento": "",
       "cep": "41905000",
       "rbase": "105",
       "nome": "PANIFICADORA E LANCHONETE I. ANDRADE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "106",
       "tipo_logradouro": "Rua",
       "logradouro": "Onze de Novembro",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Santa Cruz",
       "complemento": "",
       "cep": "41925010",
       "rbase": "106",
       "nome": "PANIF. MERC. LEMOS",
       "latitude": -13.003305,
       "longitude": -38.476658,
       "status": "E"
    },
    {
       "id": "108",
       "tipo_logradouro": "Rua",
       "logradouro": "Doutor Edíson Teixeira Barbosa",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cajazeiras",
       "complemento": "",
       "cep": "41342-165",
       "rbase": "108",
       "nome": "PANIFICADORA DOCE PAO",
       "latitude": -12.9003719,
       "longitude": -38.4013445,
       "status": "E"
    },
    {
       "id": "115",
       "tipo_logradouro": "Avenida",
       "logradouro": "Paulo VI",
       "numero": "1932",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "",
       "cep": "41.810-001",
       "rbase": "115",
       "nome": "MASANI SUPERM.",
       "latitude": -12.9899828,
       "longitude": -38.4607072,
       "status": "E"
    },
    {
       "id": "248",
       "tipo_logradouro": "Rua",
       "logradouro": "do Queimado",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Liberdade",
       "complemento": "Nº59",
       "cep": "40.325-260",
       "rbase": "248",
       "nome": "FRUTA PÃO MERC.",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "261",
       "tipo_logradouro": "2ª Travessa",
       "logradouro": "Nipônica",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Federação",
       "complemento": "",
       "cep": "40230-490",
       "rbase": "261",
       "nome": "HLENITA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "521",
       "tipo_logradouro": "Caminho",
       "logradouro": "24-Setor 02",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cajazeiras",
       "complemento": "",
       "cep": "41.340-120",
       "rbase": "521",
       "nome": "JN MERCADOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "559",
       "tipo_logradouro": "Rua",
       "logradouro": "Nossa Senhora do Resgate II",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cabula",
       "complemento": "",
       "cep": "41.150-100",
       "rbase": "559",
       "nome": "PANILHA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "762",
       "tipo_logradouro": "Rua",
       "logradouro": "Conselheiro Junqueira Ayres",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Barris",
       "complemento": "",
       "cep": "40070-080",
       "rbase": "762",
       "nome": "O BOTICARIO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "764",
       "tipo_logradouro": "Avenida",
       "logradouro": "Antônio Carlos Magalhães",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "",
       "cep": "41800-700",
       "rbase": "764",
       "nome": "O BOTICARIO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "902",
       "tipo_logradouro": "Rua",
       "logradouro": "Conde de Porto Alegre",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "IAPI",
       "complemento": "",
       "cep": "40.330-200",
       "rbase": "902",
       "nome": "G. G. ALIMENTOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "1057",
       "tipo_logradouro": "Estrada",
       "logradouro": "da Paciência",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cajazeiras",
       "complemento": "",
       "cep": "41340-050",
       "rbase": "1057",
       "nome": "MERCADO CENTRAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "1139",
       "tipo_logradouro": "Ladeira",
       "logradouro": "de Coutos",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Coutos",
       "complemento": "",
       "cep": "40.760-410",
       "rbase": "1139",
       "nome": "EBAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "1407",
       "tipo_logradouro": "Rua",
       "logradouro": "Francisco Gonçalves",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40.015-090",
       "rbase": "1407",
       "nome": "MERCEARIA DO MIRO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "1636",
       "tipo_logradouro": "Rua",
       "logradouro": "Missionário Otto Nelson",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Stella Maris",
       "complemento": "",
       "cep": "41.600-650",
       "rbase": "1636",
       "nome": "HIPERIDEAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "15428",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41.820-020",
       "rbase": "15428",
       "nome": "POSTO SUMARE",
       "latitude": -12.982088132743813,
       "longitude": -38.45533372883608,
       "status": "E"
    },
    {
       "id": "15430",
       "tipo_logradouro": "Avenida",
       "logradouro": "Oceânica",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Ondina",
       "complemento": "",
       "cep": "40.170-010",
       "rbase": "15430",
       "nome": "POSTO COELHO",
       "latitude": -13.0040924,
       "longitude": -38.504701,
       "status": "E"
    },
    {
       "id": "15431",
       "tipo_logradouro": "Rua",
       "logradouro": "Nova de Pirajá",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pirajá",
       "complemento": "",
       "cep": "41.290-010",
       "rbase": "15431",
       "nome": "POSTO 4",
       "latitude": -12.911165195797922,
       "longitude": -38.36168650674591,
       "status": "E"
    },
    {
       "id": "18124",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41.820-021",
       "rbase": "18124",
       "nome": "VERSATTO",
       "latitude": -12.9780024,
       "longitude": -38.4547378,
       "status": "E"
    },
    {
       "id": "18128",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41.820-021",
       "rbase": "18128",
       "nome": "YAN PING",
       "latitude": -12.976446,
       "longitude": -38.455755,
       "status": "E"
    },
    {
       "id": "18129",
       "tipo_logradouro": "Rua",
       "logradouro": "Minas Gerais",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "",
       "cep": "41.830-020",
       "rbase": "18129",
       "nome": "CARANGA BAR",
       "latitude": -13.006825,
       "longitude": -38.460225,
       "status": "E"
    },
    {
       "id": "18130",
       "tipo_logradouro": "Avenida",
       "logradouro": "Caminho de Areia",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho de Areia",
       "complemento": "",
       "cep": "40440-360",
       "rbase": "18130",
       "nome": "CHR PIZZARIA GAUCHAO",
       "latitude": -12.936831,
       "longitude": -38.505671,
       "status": "E"
    },
    {
       "id": "18131",
       "tipo_logradouro": "Avenida",
       "logradouro": "Estados Unidos",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40010-020",
       "rbase": "18131",
       "nome": "TREM BAO",
       "latitude": -12.9700051,
       "longitude": -38.5120136,
       "status": "E"
    },
    {
       "id": "18132",
       "tipo_logradouro": "Rua",
       "logradouro": "Conselheiro Junqueira Ayres",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Barris",
       "complemento": "",
       "cep": "40.070-080",
       "rbase": "18132",
       "nome": "BOBS",
       "latitude": -12.984558,
       "longitude": -38.512921,
       "status": "E"
    },
    {
       "id": "18133",
       "tipo_logradouro": "Rua",
       "logradouro": "Portão da Piedade",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Barris",
       "complemento": "",
       "cep": "40.070-045",
       "rbase": "18133",
       "nome": "BOBS",
       "latitude": -12.982913,
       "longitude": -38.514242,
       "status": "E"
    },
    {
       "id": "18134",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "148",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41820-020",
       "rbase": "18134",
       "nome": "PETTI GRILL",
       "latitude": -12.9840114,
       "longitude": -38.4528154,
       "status": "E"
    },
    {
       "id": "18136",
       "tipo_logradouro": "Avenida",
       "logradouro": "Sete de Setembro",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Dois de Julho",
       "complemento": "",
       "cep": "40060-001",
       "rbase": "18136",
       "nome": "LANCHES SAVOY",
       "latitude": -12.981289,
       "longitude": -38.514633,
       "status": "E"
    },
    {
       "id": "18137",
       "tipo_logradouro": "Rua",
       "logradouro": "Conde D'Eu",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40.015-320",
       "rbase": "18137",
       "nome": "CIDES RES",
       "latitude": -12.972275,
       "longitude": -38.5142763,
       "status": "E"
    },
    {
       "id": "18138",
       "tipo_logradouro": "Avenida",
       "logradouro": "Estados Unidos",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40010-020",
       "rbase": "18138",
       "nome": "HAVANA BAR E RES",
       "latitude": -12.972066,
       "longitude": -38.514163,
       "status": "E"
    },
    {
       "id": "18139",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "148",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41.820-020",
       "rbase": "18139",
       "nome": "PORTENO GRILL",
       "latitude": -12.9840378,
       "longitude": -38.4527983,
       "status": "E"
    },
    {
       "id": "18140",
       "tipo_logradouro": "Avenida",
       "logradouro": "da França",
       "numero": "164",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40010-000",
       "rbase": "18140",
       "nome": "LAN AMERICA",
       "latitude": -12.9682199,
       "longitude": -38.5092989,
       "status": "E"
    },
    {
       "id": "18141",
       "tipo_logradouro": "Avenida",
       "logradouro": "Estados Unidos",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40010-020",
       "rbase": "18141",
       "nome": "RES VIDA E SAUDE",
       "latitude": -12.9682199,
       "longitude": -38.5092989,
       "status": "E"
    },
    {
       "id": "18142",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41.820-021",
       "rbase": "18142",
       "nome": "MARIETTA SANDUICHES LEVES",
       "latitude": -12.9791526,
       "longitude": -38.4579385,
       "status": "E"
    },
    {
       "id": "18143",
       "tipo_logradouro": "Largo",
       "logradouro": "da Graça",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Graça",
       "complemento": "",
       "cep": "40150-060",
       "rbase": "18143",
       "nome": "O QUILOMBO",
       "latitude": -12.9985064,
       "longitude": -38.5230905,
       "status": "E"
    },
    {
       "id": "18144",
       "tipo_logradouro": "Conjunto",
       "logradouro": "Tiradentes",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho de Areia",
       "complemento": "",
       "cep": "40440-130",
       "rbase": "18144",
       "nome": "TCHÊ PICANHA",
       "latitude": -12.935484,
       "longitude": -38.505862,
       "status": "E"
    },
    {
       "id": "18145",
       "tipo_logradouro": "Rua",
       "logradouro": "Anísio Teixeira",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Itaigara",
       "complemento": "",
       "cep": "41.815-060",
       "rbase": "18145",
       "nome": "TOP HALS",
       "latitude": -12.99515,
       "longitude": -38.4646733,
       "status": "E"
    },
    {
       "id": "18146",
       "tipo_logradouro": "Avenida",
       "logradouro": "Antônio Carlos Magalhães",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Itaigara",
       "complemento": "",
       "cep": "41825-000",
       "rbase": "18146",
       "nome": "MARIA GULOSA",
       "latitude": -12.975831,
       "longitude": -38.459423,
       "status": "E"
    },
    {
       "id": "18147",
       "tipo_logradouro": "Avenida",
       "logradouro": "Joana Angélica",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Nazaré",
       "complemento": "",
       "cep": "40050-001",
       "rbase": "18147",
       "nome": "HALLEY BURGER",
       "latitude": -12.981113,
       "longitude": -38.512546,
       "status": "E"
    },
    {
       "id": "18148",
       "tipo_logradouro": "Praça",
       "logradouro": "Brigadeiro Faria Rocha",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Rio Vermelho",
       "complemento": "",
       "cep": "41940-440",
       "rbase": "18148",
       "nome": "REST.SABOR DE CASA",
       "latitude": -13.012819,
       "longitude": -38.486164,
       "status": "E"
    },
    {
       "id": "18149",
       "tipo_logradouro": "Avenida",
       "logradouro": "Joana Angélica",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Nazaré",
       "complemento": " ",
       "cep": "40050-001",
       "rbase": "18149",
       "nome": "LAN DOM PASSOS",
       "latitude": -12.982285,
       "longitude": -38.514157,
       "status": "E"
    },
    {
       "id": "18150",
       "tipo_logradouro": "Avenida",
       "logradouro": "Ulysses Guimarães",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Sussuarana",
       "complemento": "",
       "cep": "41.213-000",
       "rbase": "18150",
       "nome": "BAR E REST KI COMIDA",
       "latitude": -12.943201,
       "longitude": -38.430174,
       "status": "E"
    },
    {
       "id": "18151",
       "tipo_logradouro": "Rua",
       "logradouro": "Baronesa de Sauípe",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Canela",
       "complemento": "",
       "cep": "40.110-000",
       "rbase": "18151",
       "nome": "RES E LAN FLOR DO LARGO",
       "latitude": -12.9918318,
       "longitude": -38.5204638,
       "status": "E"
    },
    {
       "id": "18152",
       "tipo_logradouro": "Rua",
       "logradouro": "das Hortênsias",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "",
       "cep": "41.810-010",
       "rbase": "18152",
       "nome": "A SAUDE NA PANELA",
       "latitude": -12.992644,
       "longitude": -38.461117,
       "status": "E"
    },
    {
       "id": "18154",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41820-020",
       "rbase": "18154",
       "nome": "MR GRILL",
       "latitude": -12.9852069,
       "longitude": -38.4560755,
       "status": "E"
    },
    {
       "id": "18155",
       "tipo_logradouro": "Avenida",
       "logradouro": "Centenário",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Chame-Chame",
       "complemento": " ",
       "cep": "40155-151",
       "rbase": "18155",
       "nome": "CALIFA",
       "latitude": -12.989094,
       "longitude": -38.508059,
       "status": "E"
    },
    {
       "id": "18156",
       "tipo_logradouro": "Rua",
       "logradouro": "Marquês de Caravelas",
       "numero": "109",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Barra",
       "complemento": "",
       "cep": "40140-241",
       "rbase": "18156",
       "nome": "SUBWAY",
       "latitude": -13.0048783,
       "longitude": -38.5322777,
       "status": "E"
    },
    {
       "id": "18160",
       "tipo_logradouro": "Travessa",
       "logradouro": "São Marcos",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "São Marcos",
       "complemento": "",
       "cep": "41.253-200",
       "rbase": "18160",
       "nome": "POCKITO",
       "latitude": -12.9279249,
       "longitude": -38.4297766,
       "status": "E"
    },
    {
       "id": "18275",
       "tipo_logradouro": "Rua",
       "logradouro": "Pedro Rodrigues Bandeira",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Comércio",
       "complemento": "",
       "cep": "40.015-080",
       "rbase": "18275",
       "nome": "MANOLO REI DO PERNIL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "18574",
       "tipo_logradouro": "Avenida",
       "logradouro": "Barnabé",
       "numero": "23",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Barbalho",
       "complemento": "",
       "cep": "40301-155",
       "rbase": "18574",
       "nome": "RESTAURANTE COMER E BEBER",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19351",
       "tipo_logradouro": "",
       "logradouro": "RUA PORTAO DA PIEDADE Nº155  CENTER LAPA",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BARRIS",
       "complemento": "",
       "cep": "40070--900",
       "rbase": "19351",
       "nome": "PARMEGGIO",
       "latitude": -12.982913,
       "longitude": -38.514242,
       "status": "E"
    },
    {
       "id": "19361",
       "tipo_logradouro": "",
       "logradouro": "ESTRADA DAS BARREIRAS Nº33-A",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BARREIRAS",
       "complemento": "",
       "cep": "41.200-000",
       "rbase": "19361",
       "nome": "EBAL",
       "latitude": -12.9523885,
       "longitude": -38.460712,
       "status": "E"
    },
    {
       "id": "19362",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA BARROS REIS, S/N ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO GONÇALO",
       "complemento": "",
       "cep": "41.183-300",
       "rbase": "19362",
       "nome": "EBAL",
       "latitude": -12.958847,
       "longitude": -38.477053,
       "status": "E"
    },
    {
       "id": "19363",
       "tipo_logradouro": "",
       "logradouro": "RUA PRFº PINTO DE AGUIAR, S/N",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BOCA DO RIO",
       "complemento": "",
       "cep": "41.715-030",
       "rbase": "19363",
       "nome": "EBAL",
       "latitude": -12.9749913,
       "longitude": -38.4308805,
       "status": "E"
    },
    {
       "id": "19364",
       "tipo_logradouro": "",
       "logradouro": "RUA DA MANDICHURIA S/N",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAIXA D'AGUA",
       "complemento": "",
       "cep": "40.320-000",
       "rbase": "19364",
       "nome": "EBAL",
       "latitude": -12.9557591,
       "longitude": -38.4934665,
       "status": "E"
    },
    {
       "id": "19365",
       "tipo_logradouro": "",
       "logradouro": "RUA DIRETA DE SAO CAETANO Nº335 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SÃO CAETANO",
       "complemento": "",
       "cep": "45.601-480",
       "rbase": "19365",
       "nome": "EBAL",
       "latitude": -12.9404908,
       "longitude": -38.4715862,
       "status": "E"
    },
    {
       "id": "19369",
       "tipo_logradouro": "",
       "logradouro": "RUA OSVALDO GODILHO Nº116",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO CRISTOVAO",
       "complemento": "",
       "cep": "41.010-010",
       "rbase": "19369",
       "nome": "EBAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19372",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA CAMINHO DE AREIA LOJA A/B/C/D N 90 ",
       "numero": "138",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DE AREIA",
       "complemento": "",
       "cep": "40440000",
       "rbase": "19372",
       "nome": "DELITUTTI",
       "latitude": -12.927509,
       "longitude": -38.5033028,
       "status": "E"
    },
    {
       "id": "19373",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TIRADENTES, NR 90",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DE AREIA",
       "complemento": "",
       "cep": "40440-000",
       "rbase": "19373",
       "nome": "BAR E RES CARINHANHA",
       "latitude": -12.928439,
       "longitude": -38.494058,
       "status": "E"
    },
    {
       "id": "19375",
       "tipo_logradouro": "",
       "logradouro": "RUA PORTAO DA PIEDADE, NR 155",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PIEDADE",
       "complemento": "",
       "cep": "40070-085",
       "rbase": "19375",
       "nome": "KILOMETRO",
       "latitude": -12.982913,
       "longitude": -38.514242,
       "status": "E"
    },
    {
       "id": "19377",
       "tipo_logradouro": "",
       "logradouro": "PRAÇA PRIMEIRO DE MAIO,06",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SETE PORTAS",
       "complemento": "",
       "cep": "40255300",
       "rbase": "19377",
       "nome": "PONTO VERDE SUPERMERCADO",
       "latitude": -12.97477,
       "longitude": -38.46971,
       "status": "E"
    },
    {
       "id": "19382",
       "tipo_logradouro": "",
       "logradouro": "RUA VISCONDE DE SAO LOURENCO  N 50",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMPO GRANDE",
       "complemento": "",
       "cep": "40000-000",
       "rbase": "19382",
       "nome": "PAD FAVORITA",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19384",
       "tipo_logradouro": "",
       "logradouro": "RUA SETE DE SETEMBRO 737",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "MERCES",
       "complemento": "",
       "cep": "40 06-000",
       "rbase": "19384",
       "nome": "RESTAURANTE GRAO DE BICO",
       "latitude": -25.4302038,
       "longitude": -49.2474913,
       "status": "E"
    },
    {
       "id": "19386",
       "tipo_logradouro": "",
       "logradouro": "RUA RIO DE JANEIRO 452",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "",
       "cep": "41830-740",
       "rbase": "19386",
       "nome": "CASA VERDE",
       "latitude": -13.00087,
       "longitude": -38.457422,
       "status": "E"
    },
    {
       "id": "19387",
       "tipo_logradouro": "",
       "logradouro": "PRAÇA DORIVAL CAYME, TERREO N 50",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAPUÃ",
       "complemento": "N 50",
       "cep": "40.000-000",
       "rbase": "19387",
       "nome": "PADARIA PORTUGAL",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19388",
       "tipo_logradouro": "",
       "logradouro": "RODOVIA SSA/FEIRA - BR 324 - KM 08  ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PIRAJÁ",
       "complemento": " ",
       "cep": "41000000",
       "rbase": "19388",
       "nome": "BOMPRECO",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19389",
       "tipo_logradouro": "",
       "logradouro": "RUA ALFREDO GUIMARAES    N 117",
       "numero": "117",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "AMARALINA",
       "complemento": "",
       "cep": "41.900-424",
       "rbase": "19389",
       "nome": "FRIZEX",
       "latitude": -13.008661,
       "longitude": -38.467387,
       "status": "E"
    },
    {
       "id": "19390",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TANCREDO NEVES LOJA 04 N 148",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": " ",
       "cep": "41828-021",
       "rbase": "19390",
       "nome": "FORMAGGIO",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19391",
       "tipo_logradouro": "",
       "logradouro": "ESTRADA DO COQUEIRO GRANDE QD A LOTE 4E5",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FAZENDA GRANDE II",
       "complemento": "",
       "cep": "41.312-315",
       "rbase": "19391",
       "nome": "CHURRASCARIA QDELICIA",
       "latitude": -12.9067131,
       "longitude": -38.3965972,
       "status": "E"
    },
    {
       "id": "19392",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TANC NEVES N274 C. EMP, IGUATEMI BL B ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41.820-907",
       "rbase": "19392",
       "nome": "RES. EMPRESARIAL",
       "latitude": -12.980109,
       "longitude": -38.464294,
       "status": "E"
    },
    {
       "id": "19394",
       "tipo_logradouro": "",
       "logradouro": "RUA PADROEIRA DO BRASIL TERREO,n 78",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "VALE DAS PEDRINHAS",
       "complemento": "Nº 78",
       "cep": "41.927-140",
       "rbase": "19394",
       "nome": "PANIFICAÇÃO VILAS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19395",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA MARIO LEAL FERREIRA N 2230 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BONOCO",
       "complemento": "",
       "cep": "40.275-240",
       "rbase": "19395",
       "nome": "POSTO MATARIPE 01",
       "latitude": -12.98306132660261,
       "longitude": -38.481995723348234,
       "status": "E"
    },
    {
       "id": "19398",
       "tipo_logradouro": "",
       "logradouro": "ALAMEDA BONS AIRES  N 04",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BROTAS",
       "complemento": "",
       "cep": "40.295-230",
       "rbase": "19398",
       "nome": "DELICAT NOVA ONDINA",
       "latitude": -13.0020848,
       "longitude": -38.4889345,
       "status": "E"
    },
    {
       "id": "19400",
       "tipo_logradouro": "",
       "logradouro": "RUA MARQUES DE LEAO CASA",
       "numero": "40",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BARRA",
       "complemento": "",
       "cep": "41140-230",
       "rbase": "19400",
       "nome": "YAN PING",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19402",
       "tipo_logradouro": "",
       "logradouro": "RUA ALVARO G DE CASTRO N 382 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PIRAJÁ",
       "complemento": "",
       "cep": "41316-900",
       "rbase": "19402",
       "nome": "PORTO LANCHES",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19403",
       "tipo_logradouro": "",
       "logradouro": "RUA BORGES DOS REIS N 14",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "RIO VERMELHO",
       "complemento": "",
       "cep": "40.950-600",
       "rbase": "19403",
       "nome": "CHEIRO DE PIZZA",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19408",
       "tipo_logradouro": "",
       "logradouro": "RUA ARAUJO BOCAO N 140",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "URUGUAI",
       "complemento": " ",
       "cep": "40000-000",
       "rbase": "19408",
       "nome": "MAC DEL",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19409",
       "tipo_logradouro": "",
       "logradouro": "PRAÇA INOCENCIO GALVAO Nº07 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO PEDRO",
       "complemento": "",
       "cep": "41.000-000",
       "rbase": "19409",
       "nome": "ACOUGUE SAO LUIZ",
       "latitude": -12.9813666,
       "longitude": -38.5175689,
       "status": "E"
    },
    {
       "id": "19410",
       "tipo_logradouro": "",
       "logradouro": "VASCO DA GAMA 4615",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "VASCO DA GAMA",
       "complemento": "",
       "cep": "40.307-300",
       "rbase": "19410",
       "nome": "MCDONALD'S",
       "latitude": -12.579738,
       "longitude": -41.7007272,
       "status": "E"
    },
    {
       "id": "19453",
       "tipo_logradouro": "",
       "logradouro": "PRAÇA CONSELHEIRO  ALAMIEDA COUTO 6  ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "NAZARÉ",
       "complemento": " ",
       "cep": "40050470",
       "rbase": "19453",
       "nome": "BOMPRECO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19485",
       "tipo_logradouro": "",
       "logradouro": "RUA PORTAO DA PIEDADE  SHOP LAPA",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PIEDADE",
       "complemento": "",
       "cep": "40070-900",
       "rbase": "19485",
       "nome": "CUPIM PAO DE BATATA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19490",
       "tipo_logradouro": "",
       "logradouro": "RUA CONEGO PEREIRA Nº31",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "DOIS LEOES",
       "complemento": "",
       "cep": "40.300-270",
       "rbase": "19490",
       "nome": "MINAS PNEUS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19516",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TACREDO NEVES 148 LOJAS, N° 12/13 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41.828-900",
       "rbase": "19516",
       "nome": "OTICA DA GENTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19538",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA CENTENÁRIO Nº 2883 ED VIT. CENTER LJ ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CHAME-CHAME",
       "complemento": "",
       "cep": "40.551-150",
       "rbase": "19538",
       "nome": "ANDRE LANCHES",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19551",
       "tipo_logradouro": "",
       "logradouro": "LARGO EUCLIDES DA CUNHA Nº74E",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SARAMANDAIA",
       "complemento": "",
       "cep": "41.000-540",
       "rbase": "19551",
       "nome": "SUPERMERCADO IRMAOS RODRIGUES",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19562",
       "tipo_logradouro": "",
       "logradouro": "QD. A CAMINHO 12 n°05",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FAZENDA GRANDE",
       "complemento": "Nº05",
       "cep": "41300360",
       "rbase": "19562",
       "nome": "MERC.IDEAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19565",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA ACM EDF.EMPRESARIAL TORRE DO PARQUE LJ-05,Nº771 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": "",
       "cep": "41.850-000",
       "rbase": "19565",
       "nome": "CAFETERIA DA TORRE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19574",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA ANTÔNIO CARLOS MAGALHÃES LOJA 2 Nº4451  ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "IGUATEMI",
       "complemento": " ",
       "cep": "41850-000",
       "rbase": "19574",
       "nome": "AMPM EXPRESS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19579",
       "tipo_logradouro": "",
       "logradouro": "RUA PORTÃO DA PIEDADE SHOPPING C. LAPA PV L1 LJ.4",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PIEDADE",
       "complemento": "",
       "cep": "40070-000",
       "rbase": "19579",
       "nome": "PASSE AQUI LANCHES",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19769",
       "tipo_logradouro": "",
       "logradouro": "RUA TEIXEIRA DE FREITAS SHOPPING CENTER LAPA NR 1",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PIEDADE",
       "complemento": "",
       "cep": "40.070-000",
       "rbase": "19769",
       "nome": "YAN PING",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19826",
       "tipo_logradouro": "",
       "logradouro": "RUA D QD 24 LOTE 79",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FAZENDA COUTOS III",
       "complemento": "",
       "cep": "40.801-970",
       "rbase": "19826",
       "nome": "PANIFICADORA COUTO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19837",
       "tipo_logradouro": "",
       "logradouro": "RUA ANA PIEDADE,",
       "numero": "17",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "JARDIM LOBATO",
       "complemento": "",
       "cep": "40480280",
       "rbase": "19837",
       "nome": "SUPERMERCADO BOI BOM",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19870",
       "tipo_logradouro": "",
       "logradouro": "RUA MARIO KERTS Nº63",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SANTA MONICA",
       "complemento": "",
       "cep": "40.340-000",
       "rbase": "19870",
       "nome": "MERCADO EVARISTO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "19885",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TANCREDO NEVES SHOP IGUATEMI LJ24 Nº148 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "",
       "cep": "41828900",
       "rbase": "19885",
       "nome": "O BOTICARIO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "20027",
       "tipo_logradouro": "",
       "logradouro": "S D N CONJ A 2 SUBSOLO LOJA 20  ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "B. V. DE SAO CAETANO",
       "complemento": " ",
       "cep": "70077900",
       "rbase": "20027",
       "nome": "PAO DE ACUCAR",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "20043",
       "tipo_logradouro": "",
       "logradouro": "RUA BRUNO SEABRA LOJA 02 TERREO N 36",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "LAPINHA",
       "complemento": "",
       "cep": "40376-510",
       "rbase": "20043",
       "nome": "PAO PANNYS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "21501",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TANCREDO NEVES 1672 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41.000-000",
       "rbase": "21501",
       "nome": "NUTRICASH",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "21514",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA PAULO VI   N 266",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "",
       "cep": "41.810-001",
       "rbase": "21514",
       "nome": "LANCHONETE MARIA DE LOURDES",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "21515",
       "tipo_logradouro": "",
       "logradouro": "RUA NOVO PARAÍSO  N 35",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ARMAÇÃO",
       "complemento": "",
       "cep": "41.750-280",
       "rbase": "21515",
       "nome": "CASA DE CARNE DOIS AMIGOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "21529",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA ANTONIO CARLOS MAGALHÃES Nº 1034 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "",
       "cep": "41830-030",
       "rbase": "21529",
       "nome": "SALVAPÉ",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "21544",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA ANTÔNIO CARLOS MAGALHÃES",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SANTA TERESA",
       "complemento": "",
       "cep": "40.265-200",
       "rbase": "21544",
       "nome": "POSTO METRO E EXPRES",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "23173",
       "tipo_logradouro": "",
       "logradouro": "RUA DIRETA DO SABOEIRO N 72 LOJA",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SABOEIRO",
       "complemento": "",
       "cep": "41.180-540",
       "rbase": "23173",
       "nome": "FIAES ALINHAMENTO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25217",
       "tipo_logradouro": "",
       "logradouro": "RODOVIA BA526",
       "numero": "301",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO CRISTOVAO",
       "complemento": "",
       "cep": "41.510-000",
       "rbase": "25217",
       "nome": "SUBWAY",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25218",
       "tipo_logradouro": "",
       "logradouro": "RUA ILHEUS - L1 - EDF LIGTH CENTER",
       "numero": "36",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "RIO VERMELHO",
       "complemento": " ",
       "cep": "41.940-570",
       "rbase": "25218",
       "nome": "SUBWAY",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25240",
       "tipo_logradouro": "",
       "logradouro": "R Anisio Teixeira",
       "numero": "161",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": "",
       "cep": "41815-900",
       "rbase": "25240",
       "nome": "MARIPOSA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25241",
       "tipo_logradouro": "",
       "logradouro": "RUA ANISIO TEIXEIRA, LJ 32, TERREO",
       "numero": "161",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": " ",
       "cep": "41.815-900",
       "rbase": "25241",
       "nome": "MARIPOSA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25474",
       "tipo_logradouro": "",
       "logradouro": "AV ANTO CARLOS MAGALHAES",
       "numero": "4925",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "IGUATEMI",
       "complemento": "BLOCO A",
       "cep": "40.280-000",
       "rbase": "25474",
       "nome": "EUROVIA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25475",
       "tipo_logradouro": "Avenida",
       "logradouro": "AV ANTONIO CARLOS MAGALHAES, 4925, BLOCO A",
       "numero": ".",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "IGUATEMI",
       "complemento": " ",
       "cep": "40.280000",
       "rbase": "25475",
       "nome": "EUROVIA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25523",
       "tipo_logradouro": "",
       "logradouro": "Avenida CentenÃ¡rio",
       "numero": "328",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CHAME-CHAME",
       "complemento": " ",
       "cep": "40155-150",
       "rbase": "25523",
       "nome": "AUTO POSTO CENTENARIO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25581",
       "tipo_logradouro": "",
       "logradouro": "AV OTAVIO MANGABEIRA",
       "numero": "1492",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAPOA",
       "complemento": "",
       "cep": "41.610-160",
       "rbase": "25581",
       "nome": "POSTO BONFIM",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25808",
       "tipo_logradouro": "",
       "logradouro": "R PADRE JOSE HENRIQUE",
       "numero": "02",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "NORDESTE  AMARALINA",
       "complemento": "",
       "cep": "41.905-400",
       "rbase": "25808",
       "nome": "MERCADINHO SOL NASCENTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25809",
       "tipo_logradouro": "",
       "logradouro": "RUA PADRE JOSE HENRIQUE",
       "numero": "02",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "NORDESTE  AMARALINA",
       "complemento": " ",
       "cep": "41.905-400",
       "rbase": "25809",
       "nome": "MERCADINHO SOL NASCENTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26158",
       "tipo_logradouro": "",
       "logradouro": "Rua Minas Gerais",
       "numero": "629",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "",
       "cep": "41830-020",
       "rbase": "26158",
       "nome": "MINAS MAR SUPERMERCADO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26159",
       "tipo_logradouro": "",
       "logradouro": "RUA MINAS GERAIS",
       "numero": "629",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": " ",
       "cep": "41.830-020",
       "rbase": "26159",
       "nome": "MINAS MAR SUPERMERCADO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26297",
       "tipo_logradouro": "",
       "logradouro": "AV ANTO. CARLOS MAGALHAES",
       "numero": "4925",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "IGUATEMI",
       "complemento": "BL B",
       "cep": "40.280-000",
       "rbase": "26297",
       "nome": "EUROVIA NISSAN",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26298",
       "tipo_logradouro": "",
       "logradouro": "AV ANTONIO CARLOS MAGALHAES, 4925, BLOCO B",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "IGUATEMI",
       "complemento": " ",
       "cep": "40.280-000",
       "rbase": "26298",
       "nome": "EUROVIA NISSAN",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26403",
       "tipo_logradouro": "",
       "logradouro": "AV ANTONIO CARLOS MAGALHA",
       "numero": "846",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": "",
       "cep": "41.825-000",
       "rbase": "26403",
       "nome": "MUNDO VERDE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26404",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA ACM - LJ 1",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": " ",
       "cep": "41.825-000",
       "rbase": "26404",
       "nome": "MUNDO VERDE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26986",
       "tipo_logradouro": "",
       "logradouro": "RUA SAO MARCOS ",
       "numero": "47",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": "LOJA E",
       "cep": "41.253-281",
       "rbase": "26986",
       "nome": "ARMARINHO PEIXOTO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26987",
       "tipo_logradouro": "",
       "logradouro": "RUA SAO MARCOS, - LOJA E",
       "numero": "47",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": " ",
       "cep": "41.253-281",
       "rbase": "26987",
       "nome": "ARMARINHO PEIXOTO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26990",
       "tipo_logradouro": "",
       "logradouro": "R ONZE DE NOVEMBRO",
       "numero": "766",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SANTA CRUZ",
       "complemento": "",
       "cep": "41.925-010",
       "rbase": "26990",
       "nome": "MERCADINHO SOL NASCENTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26991",
       "tipo_logradouro": "",
       "logradouro": "RUA ONZE DE NOVEMBRO - NOME FANT MERC SOL NASCEN ",
       "numero": "766",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SANTA CRUZ",
       "complemento": " ",
       "cep": "41.925-010",
       "rbase": "26991",
       "nome": "MERCADINHO SOL NASCENTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27010",
       "tipo_logradouro": " ",
       "logradouro": "Ladeira do Arco",
       "numero": "88",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BARBALHO",
       "complemento": " ",
       "cep": "40.301146",
       "rbase": "27010",
       "nome": "POSTO BARBALHO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27011",
       "tipo_logradouro": " ",
       "logradouro": "LADEIRA DO ARCO",
       "numero": "88",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BARBALHO",
       "complemento": " ",
       "cep": "40.301146",
       "rbase": "27011",
       "nome": "POSTO BARBALHO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27078",
       "tipo_logradouro": "",
       "logradouro": "AV ANITA GARIBALDI",
       "numero": "1651",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FEDERACAO",
       "complemento": "",
       "cep": "40.210-750",
       "rbase": "27078",
       "nome": "AUTO POSTO BERIMBAU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27079",
       "tipo_logradouro": "",
       "logradouro": "AV ANITA GARIBALDI",
       "numero": "1651",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FEDERACAO",
       "complemento": "",
       "cep": "40210-750",
       "rbase": "27079",
       "nome": "AUTO POSTO BERIMBAU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27098",
       "tipo_logradouro": "",
       "logradouro": "Estrada de Campinas",
       "numero": "818",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO CAETANO",
       "complemento": "",
       "cep": "40.391-161",
       "rbase": "27098",
       "nome": "POSTO SAO CAETANO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27099",
       "tipo_logradouro": "",
       "logradouro": "RUA QUINTAS DOS LAZAROS",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": " ",
       "cep": "40.300-315",
       "rbase": "27099",
       "nome": "POSTO SAO CAETANO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27134",
       "tipo_logradouro": "",
       "logradouro": "PC VISCONDE DE CAIRU",
       "numero": "SN",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "COMERCIO",
       "complemento": "",
       "cep": "40.015-000",
       "rbase": "27134",
       "nome": "POSTO DA RAMPA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27135",
       "tipo_logradouro": "",
       "logradouro": "RUA QUINTAS DOS LAZAROS",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": " ",
       "cep": "40.300-315",
       "rbase": "27135",
       "nome": "POSTO DA RAMPA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27136",
       "tipo_logradouro": "",
       "logradouro": "Avenida Afranio Peixoto",
       "numero": "5444",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PLATAFORMA",
       "complemento": "",
       "cep": "40.717-140",
       "rbase": "27136",
       "nome": "POSTO ESSO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27137",
       "tipo_logradouro": "",
       "logradouro": "RUA QUINTAS DOS LAZAROS",
       "numero": "193",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": " ",
       "cep": "40.300-315",
       "rbase": "27137",
       "nome": "POSTO ESSO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27138",
       "tipo_logradouro": "",
       "logradouro": "Rua Quintas dos Lazaros",
       "numero": "SN",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": "",
       "cep": "40.300-315",
       "rbase": "27138",
       "nome": "POSTO SAO JUDAS TADEU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27139",
       "tipo_logradouro": "",
       "logradouro": "RUA QUINTAS DOS LAZAROS",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": " ",
       "cep": "40.300-315",
       "rbase": "27139",
       "nome": "POSTO SAO JUDAS TADEU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27255",
       "tipo_logradouro": "",
       "logradouro": "R QUINTAS DOS LAZAROS - POSTO SÃO JUDAS TADEU",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": " ",
       "cep": "40.300-315",
       "rbase": "27255",
       "nome": "POS ITACIMIRIM",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27256",
       "tipo_logradouro": "",
       "logradouro": "Praca Cons. Joao Alfredo",
       "numero": "SN",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAIXA D'AGUA",
       "complemento": "",
       "cep": "40.320-350",
       "rbase": "27256",
       "nome": "POSTO TAMARINEIRO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27257",
       "tipo_logradouro": "",
       "logradouro": "RUA QUINTA DOS LAZAROS ",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BAIXA DE QUINTAS",
       "complemento": " ",
       "cep": "40.300-315",
       "rbase": "27257",
       "nome": "POSTO TAMARINEIRO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27315",
       "tipo_logradouro": "",
       "logradouro": "AV TANCREDO NEVES, SALVADOR SHOPING",
       "numero": "3054",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41.820-020",
       "rbase": "27315",
       "nome": "SALAD CREATIONS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27316",
       "tipo_logradouro": "",
       "logradouro": "AV TANCREDO NEVES, SALVADOR SHOPING",
       "numero": "3054",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ÁRVORES",
       "complemento": "",
       "cep": "41.820-020",
       "rbase": "27316",
       "nome": "SALAD CREATIONS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27763",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA JOÃO MARTINS NR.21  ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARIPE",
       "complemento": " ",
       "cep": "40000-000",
       "rbase": "27763",
       "nome": "COMERCIAL PEREIRA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27770",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA AFRANIO PEIXOTO, 14 A",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "LOBATO",
       "complemento": "",
       "cep": "40.470-630",
       "rbase": "27770",
       "nome": "POSTO IPANEMA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27927",
       "tipo_logradouro": "",
       "logradouro": "Avenida Joana Angélica",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "NAZARÉ",
       "complemento": "",
       "cep": "40.050-001",
       "rbase": "27927",
       "nome": "TROPICALIA FRIOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28329",
       "tipo_logradouro": "",
       "logradouro": "Avenida Vasco da Gama",
       "numero": "4838",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "RIO VERMELHO",
       "complemento": " ",
       "cep": "40240-090",
       "rbase": "28329",
       "nome": "POSTO NT 10 OXALA BA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28330",
       "tipo_logradouro": " ",
       "logradouro": "Avenida Vasco da Gama",
       "numero": "4838",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FEDERAÇÃO",
       "complemento": " ",
       "cep": "40.230731",
       "rbase": "28330",
       "nome": "POSTO NT 10 OXALA BA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28384",
       "tipo_logradouro": "",
       "logradouro": "AV. TANCREDO NEVES - EDF. MUNDO PLAZA - SL 2901",
       "numero": "620",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ÁRVORES",
       "complemento": " ",
       "cep": "41.820-020",
       "rbase": "28384",
       "nome": "POSTO KALILANDIA I",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28570",
       "tipo_logradouro": "",
       "logradouro": "RUA 25 DE DEZEMBRO BARIRI",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ENGENHO VELHO BROTAS",
       "complemento": "",
       "cep": "40.240-715",
       "rbase": "28570",
       "nome": "MERCEARIAL NACIONAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28571",
       "tipo_logradouro": "",
       "logradouro": "PRAÇA DO CABRITO",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ALTO DO CABRITO",
       "complemento": "",
       "cep": "40.484-655",
       "rbase": "28571",
       "nome": "MERCADINHO TEIXEIRA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28812",
       "tipo_logradouro": "",
       "logradouro": "AV DOURIVAL CAYMMI",
       "numero": "1001",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAPUA",
       "complemento": "",
       "cep": "41.635-150",
       "rbase": "28812",
       "nome": "POSTO PORTAL DE ITAPUA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28813",
       "tipo_logradouro": "",
       "logradouro": "RUA DOURIVAL CAYMMI ",
       "numero": "1001",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAPUA",
       "complemento": " ",
       "cep": "41.635-150",
       "rbase": "28813",
       "nome": "POSTO PORTAL DE ITAPUA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29075",
       "tipo_logradouro": "",
       "logradouro": "Avenida Luis Eduardo Magalhaes",
       "numero": "3301",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CABULA VII",
       "complemento": "",
       "cep": "41.150-595",
       "rbase": "29075",
       "nome": "MORENA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29076",
       "tipo_logradouro": "",
       "logradouro": "AV LUIZ EDUARDO MAGALHÃES, N° 3301A CABULA",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "STIEP",
       "complemento": " ",
       "cep": "41.150-595",
       "rbase": "29076",
       "nome": "MORENA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29081",
       "tipo_logradouro": "",
       "logradouro": "Rodovia BA 526",
       "numero": "1046",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CASSANGE",
       "complemento": "",
       "cep": "41.505-220",
       "rbase": "29081",
       "nome": "PANI HAUSE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29082",
       "tipo_logradouro": "",
       "logradouro": "RODOVIA BA -526 - CIA AEROPORTO",
       "numero": "1046",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CASSANGE",
       "complemento": " ",
       "cep": "41.505-220",
       "rbase": "29082",
       "nome": "PANI HAUSE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29925",
       "tipo_logradouro": "",
       "logradouro": "ESTRADA DAS BARREIRAS Nº 210 E",
       "numero": "SN",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CABULA",
       "complemento": " ",
       "cep": "41200-010",
       "rbase": "29925",
       "nome": "MERCADINHO BARREIRAS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29926",
       "tipo_logradouro": "",
       "logradouro": "Estrada das Barreiras",
       "numero": "210 E",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ESTRADA S BARREIRAS",
       "complemento": " ",
       "cep": "41.195-000",
       "rbase": "29926",
       "nome": "MERCADINHO BARREIRAS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "32149",
       "tipo_logradouro": "Avenida",
       "logradouro": "Tancredo Neves",
       "numero": "3413",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pernambués",
       "complemento": " ",
       "cep": "41100800",
       "rbase": "32149",
       "nome": "ATACAD MAKRO LJ28 Salvador",
       "latitude": -12.976215,
       "longitude": -38.460408,
       "status": "E"
    },
    {
       "id": "32694",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA TANCREDO NEVES 2915",
       "numero": "3133",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "PISO L3, LJ 3024, SS",
       "cep": "41826-021",
       "rbase": "32694",
       "nome": "IL POLO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "32695",
       "tipo_logradouro": " ",
       "logradouro": "Rua Coronel Almerindo Rehem",
       "numero": "82",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ÁRVORES",
       "complemento": "EDF. BAHIA EXECUTIVE CENTER SL305",
       "cep": "41.820768",
       "rbase": "32695",
       "nome": "IL POLO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "35722",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA JORGE AMADO  N 01 ",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BOCA DO RIO",
       "complemento": "",
       "cep": "41715-330",
       "rbase": "35722",
       "nome": " ",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "37797",
       "tipo_logradouro": "",
       "logradouro": "Avenida Professor Manoel Ribeiro",
       "numero": "861",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "STIEP",
       "complemento": " ",
       "cep": "41770-095",
       "rbase": "37797",
       "nome": "POSTO FLAMINGO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "37798",
       "tipo_logradouro": "",
       "logradouro": "Avenida Professor Manoel Ribeiro",
       "numero": "736",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "STIEP",
       "complemento": " ",
       "cep": "41.750-160",
       "rbase": "37798",
       "nome": "POSTO FLAMINGO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "39958",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA OCTAVIO MANGABEIRA   7253",
       "numero": "10",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BOCA DO RIO",
       "complemento": " ",
       "cep": "41706-690",
       "rbase": "39958",
       "nome": "POSTO MARIA CAFE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "40091",
       "tipo_logradouro": "",
       "logradouro": "AVENIDA GENARO DE CARVALHO S/N",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CASTELO BRANCO",
       "complemento": "",
       "cep": "41.320-100",
       "rbase": "40091",
       "nome": " ",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "40939",
       "tipo_logradouro": "",
       "logradouro": "RUA NOSSA SENHORA DO CARMO Nº117",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SETE DE ABRIL",
       "complemento": "",
       "cep": "41.385-040",
       "rbase": "40939",
       "nome": " ",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    }
 ]

}
