export function loadLists() {
  return [
    {
       "id": "1",
       "numero": "450",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "Suarez Trade, Sala 2402",
       "cep": "41820020",
       "rbase": "1",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": -12.977854,
       "longitude": -38.460552,
       "status": "E"
    },
    {
       "id": "2",
       "numero": "1672",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "Edif. Catabas Empresarial, 4 Andar",
       "cep": "41820020",
       "rbase": "2",
       "nome": "NUTRICASH TESTE 1",
       "latitude": -12.977854,
       "longitude": -38.460552,
       "status": "E"
    },
    {
       "id": "1176",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Boa Vista",
       "complemento": "",
       "cep": "50060080",
       "rbase": "1176",
       "nome": "FIGUEIRAS CALCADOS LTDA",
       "latitude": -8.061391,
       "longitude": -34.884507,
       "status": "E"
    },
    {
       "id": "1412",
       "numero": "",
       "estado": "MA",
       "cidade": "São Luís",
       "bairro": "Turu",
       "complemento": "",
       "cep": "65066320",
       "rbase": "1412",
       "nome": "FRIBAL FRANCHISING",
       "latitude": -2.516359,
       "longitude": -44.222956,
       "status": "E"
    },
    {
       "id": "1857",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Rio Vermelho",
       "complemento": "",
       "cep": "41940-060",
       "rbase": "1857",
       "nome": "MORENA VEICULOS",
       "latitude": -13.0096791,
       "longitude": -38.4863064,
       "status": "E"
    },
    {
       "id": "1927",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Federação",
       "complemento": "",
       "cep": "40.230-731",
       "rbase": "1927",
       "nome": "PERINI ALIMENTOS",
       "latitude": -12.989057,
       "longitude": -38.507464,
       "status": "E"
    },
    {
       "id": "5826",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Trobogy",
       "complemento": "",
       "cep": "41.745-130",
       "rbase": "5826",
       "nome": "BRUNE VEICULOS",
       "latitude": -12.9315654,
       "longitude": -38.40873,
       "status": "E"
    },
    {
       "id": "5891",
       "numero": "",
       "estado": "BA",
       "cidade": "Feira de Santana",
       "bairro": "Centro",
       "complemento": "",
       "cep": "44.001-615",
       "rbase": "5891",
       "nome": "NORAUTO VEICULOS LTDA",
       "latitude": -12.259832,
       "longitude": -38.956729,
       "status": "E"
    },
    {
       "id": "5892",
       "numero": "",
       "estado": "BA",
       "cidade": "Feira de Santana",
       "bairro": "Santa Mônica",
       "complemento": "",
       "cep": "44.077-750",
       "rbase": "5892",
       "nome": "JUBIABA VEICULOS",
       "latitude": -12.267532,
       "longitude": -38.941582,
       "status": "E"
    },
    {
       "id": "5893",
       "numero": "",
       "estado": "BA",
       "cidade": "Feira de Santana",
       "bairro": "Santa Mônica",
       "complemento": "",
       "cep": "44.077-760",
       "rbase": "5893",
       "nome": "JACUIPE VEICULOS",
       "latitude": -12.260223,
       "longitude": -38.953741,
       "status": "E"
    },
    {
       "id": "8889",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Brotas",
       "complemento": "",
       "cep": "40.285-600",
       "rbase": "8889",
       "nome": "FAAST",
       "latitude": -12.982812,
       "longitude": -38.482259,
       "status": "E"
    },
    {
       "id": "14300",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Canela",
       "complemento": "",
       "cep": "40.110-100",
       "rbase": "14300",
       "nome": "MARVEL",
       "latitude": -12.992277,
       "longitude": -38.524472,
       "status": "E"
    },
    {
       "id": "15537",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Água Fria",
       "complemento": "",
       "cep": "52.130-000",
       "rbase": "15537",
       "nome": "POSTO FERRARI",
       "latitude": -8.01902,
       "longitude": -34.89379,
       "status": "E"
    },
    {
       "id": "15542",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Santo Amaro",
       "complemento": "",
       "cep": "50.040-000",
       "rbase": "15542",
       "nome": "POSTO TACARUNA",
       "latitude": -8.046785,
       "longitude": -34.876543,
       "status": "E"
    },
    {
       "id": "15543",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Boa Viagem",
       "complemento": "",
       "cep": "51.020-370",
       "rbase": "15543",
       "nome": "POSTO MODELO",
       "latitude": -8.128143,
       "longitude": -34.900667,
       "status": "E"
    },
    {
       "id": "15544",
       "numero": "",
       "estado": "PE",
       "cidade": "Olinda",
       "bairro": "Rio Doce",
       "complemento": "",
       "cep": "53.040-150",
       "rbase": "15544",
       "nome": "POSTO XINGU LTDA",
       "latitude": -7.9669984,
       "longitude": -34.8381264,
       "status": "E"
    },
    {
       "id": "15546",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Parnamirim",
       "complemento": "",
       "cep": "52.060-010",
       "rbase": "15546",
       "nome": "POSTO XINGU",
       "latitude": -8.035299,
       "longitude": -34.90884,
       "status": "E"
    },
    {
       "id": "15547",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Jardim São Paulo",
       "complemento": "",
       "cep": "50.790-640",
       "rbase": "15547",
       "nome": "POSTO XINGU",
       "latitude": -8.071259,
       "longitude": -34.960792,
       "status": "E"
    },
    {
       "id": "15582",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Recife",
       "complemento": "",
       "cep": "50.030-230",
       "rbase": "15582",
       "nome": "POSTO APOLO",
       "latitude": -8.057191,
       "longitude": -34.872363,
       "status": "E"
    },
    {
       "id": "15583",
       "numero": "",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Imbiribeira",
       "complemento": "",
       "cep": "51.170-000",
       "rbase": "15583",
       "nome": "MEGA POSTO",
       "latitude": -8.092288,
       "longitude": -34.909002,
       "status": "E"
    },
    {
       "id": "15648",
       "numero": "",
       "estado": "PE",
       "cidade": "Santo Agostinho",
       "bairro": "CIDADE GARAPU",
       "complemento": "",
       "cep": "54.590-000",
       "rbase": "15648",
       "nome": "PETRO CABO",
       "latitude": -8.325033,
       "longitude": -34.951243,
       "status": "E"
    },
    {
       "id": "15651",
       "numero": "",
       "estado": "PE",
       "cidade": "Jaboatão dos Guararapes",
       "bairro": "Manassu",
       "complemento": "",
       "cep": "54.130-340",
       "rbase": "15651",
       "nome": "VILA BELA",
       "latitude": -8.077815,
       "longitude": -34.979325,
       "status": "E"
    },
    {
       "id": "15791",
       "numero": "1651",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Federação",
       "complemento": "",
       "cep": "40.210-750",
       "rbase": "15791",
       "nome": "MEGA POSTO BERIMBAU",
       "latitude": -13.0028199,
       "longitude": -38.502878,
       "status": "E"
    },
    {
       "id": "17336",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Brotas",
       "complemento": "",
       "cep": "40.285-001",
       "rbase": "17336",
       "nome": "MEGA POSTO BROTAS",
       "latitude": -12.988355,
       "longitude": -38.492743,
       "status": "E"
    },
    {
       "id": "18317",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41.820-021",
       "rbase": "18317",
       "nome": "SALAD CREATIONS",
       "latitude": -12.9780024,
       "longitude": -38.4547378,
       "status": "E"
    },
    {
       "id": "18610",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "São Cristóvão",
       "complemento": "",
       "cep": "41.510-000",
       "rbase": "18610",
       "nome": "SUBWAY",
       "latitude": -12.9079278,
       "longitude": -38.3505189,
       "status": "E"
    },
    {
       "id": "19073",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Campinas de Pirajá",
       "complemento": "",
       "cep": "41.270-515",
       "rbase": "19073",
       "nome": "NUTRIGOLDEN",
       "latitude": -12.926993,
       "longitude": -38.46885,
       "status": "E"
    },
    {
       "id": "19073",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Campinas de Pirajá",
       "complemento": "",
       "cep": "41.270-515",
       "rbase": "19073",
       "nome": "NUTRIGOLDEN ESTALEIRO",
       "latitude": -12.926993,
       "longitude": -38.46885,
       "status": "E"
    },
    {
       "id": "19525",
       "numero": "",
       "estado": "PE",
       "cidade": "RECIFE",
       "bairro": "AFOGADOS",
       "complemento": "",
       "cep": "50.750-000",
       "rbase": "19525",
       "nome": "POSTO ELO",
       "latitude": -8.073258,
       "longitude": -34.907989,
       "status": "E"
    },
    {
       "id": "19528",
       "numero": "",
       "estado": "PE",
       "cidade": "RECIFE",
       "bairro": "ILHA DO LEITE",
       "complemento": "",
       "cep": "50.070-270",
       "rbase": "19528",
       "nome": "POSTO ILHEUS",
       "latitude": -8.063046,
       "longitude": -34.897439,
       "status": "E"
    },
    {
       "id": "20948",
       "numero": "",
       "estado": "PE",
       "cidade": "SAO LOURENCO DA MATA",
       "bairro": "CENTRO",
       "complemento": "",
       "cep": "54.730-970",
       "rbase": "20948",
       "nome": "MASTER POSTO",
       "latitude": -8.8137173,
       "longitude": -36.954107,
       "status": "E"
    },
    {
       "id": "23163",
       "numero": "805",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "9 ANDAR",
       "cep": "41820021",
       "rbase": "23163",
       "nome": "INSTITUTO RECONCAVO",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "23164",
       "numero": "",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41820021",
       "rbase": "23164",
       "nome": "INSTITUTO RECONCAVO",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "23165",
       "numero": "805",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "9 ANDAR",
       "cep": "41820021",
       "rbase": "23165",
       "nome": "INSTITUTO RECONCAVO",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "23782",
       "numero": "71",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO BENTO",
       "complemento": "",
       "cep": "40393-280",
       "rbase": "23782",
       "nome": "EDF. EXECUTIVO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "23783",
       "numero": " 71",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO BENTO",
       "complemento": "",
       "cep": "40393-280",
       "rbase": "23783",
       "nome": "EDF. EXECUTIVO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "23810",
       "numero": "148",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "LJ 25",
       "cep": "41820-908",
       "rbase": "23810",
       "nome": "VIVA VERDE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "23811",
       "numero": "148",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "LJ 25",
       "cep": "41820-908",
       "rbase": "23811",
       "nome": "VIVA VERDE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "23812",
       "numero": "20",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "VILAS DO ATLANTICO",
       "complemento": "LOT 02",
       "cep": "42700-001",
       "rbase": "23812",
       "nome": "COND. VERT VILAS DO ATL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "23813",
       "numero": "20",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "VILAS DO ATLANTICO",
       "complemento": "LOT 02",
       "cep": "42700-001",
       "rbase": "23813",
       "nome": "COND. VERT VILAS DO ATL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24155",
       "numero": "100",
       "estado": "BA",
       "cidade": "Camaçari",
       "bairro": "Ponto Certo",
       "complemento": "",
       "cep": "42801170",
       "rbase": "24155",
       "nome": "QUALYTEC",
       "latitude": -12.704899,
       "longitude": -38.312208,
       "status": "E"
    },
    {
       "id": "24215",
       "numero": "192",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARQUE BELA VISTA",
       "complemento": "Terreo",
       "cep": "40279-150",
       "rbase": "24215",
       "nome": "ENTEL LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24216",
       "numero": "192",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARQUE BELA VISTA",
       "complemento": "Terreo",
       "cep": "40279-150",
       "rbase": "24216",
       "nome": "ENTEL LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24230",
       "numero": "KM 2",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "ESTRADA DO COCO",
       "complemento": "SHOP LIT",
       "cep": "72.700-000",
       "rbase": "24230",
       "nome": "COND SOL DO FLAMENGO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24231",
       "numero": "6061",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Aracuí",
       "complemento": "",
       "cep": "42702010",
       "rbase": "24231",
       "nome": "COND SOL DO FLAMENGO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24419",
       "numero": "500",
       "estado": "BA",
       "cidade": "Camaçari",
       "bairro": "Gravatá",
       "complemento": "",
       "cep": "42807171",
       "rbase": "24419",
       "nome": "ISOTEL LOCACOES",
       "latitude": -12.690847,
       "longitude": -38.336331,
       "status": "E"
    },
    {
       "id": "24529",
       "numero": "100",
       "estado": "BA",
       "cidade": "Camaçari",
       "bairro": "Ponto Certo",
       "complemento": "2 andar sala 205",
       "cep": "42801170",
       "rbase": "24529",
       "nome": "QUALYTEC",
       "latitude": -12.704899,
       "longitude": -38.312208,
       "status": "E"
    },
    {
       "id": "24624",
       "numero": "74",
       "estado": "BA",
       "cidade": "Ilhéus",
       "bairro": "Cidade Nova",
       "complemento": "EDF PREMIER BUSINESS CENTER, SL 912",
       "cep": "45652130",
       "rbase": "24624",
       "nome": "SUNSET",
       "latitude": -14.788584,
       "longitude": -39.03431,
       "status": "E"
    },
    {
       "id": "24684",
       "numero": "160",
       "estado": "BA",
       "cidade": "ITABUNA",
       "bairro": "FATIMA",
       "complemento": "",
       "cep": "45603--445",
       "rbase": "24684",
       "nome": "CHILLER REFRIGERACAO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24685",
       "numero": "160",
       "estado": "BA",
       "cidade": "ITABUNA",
       "bairro": "FATIMA",
       "complemento": "",
       "cep": "45603--445",
       "rbase": "24685",
       "nome": "CHILLER REFRIGERACAO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24721",
       "numero": "1672",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "- lado par",
       "cep": "41820020",
       "rbase": "24721",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "24722",
       "numero": "1672",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41820020",
       "rbase": "24722",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "24773",
       "numero": "1672",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "4 ANDAR",
       "cep": "41.820-020",
       "rbase": "24773",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24774",
       "numero": "1672",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ÁRVORES",
       "complemento": "",
       "cep": "41.820-020",
       "rbase": "24774",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24811",
       "numero": "14",
       "estado": "BA",
       "cidade": "ALAGOINHAS",
       "bairro": "CENTRO",
       "complemento": "SL 101",
       "cep": "48010-150",
       "rbase": "24811",
       "nome": "CANUDOS SERVICOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24812",
       "numero": "14",
       "estado": "BA",
       "cidade": "ALAGOINHAS",
       "bairro": "CENTRO",
       "complemento": "SL 101",
       "cep": "48010-150",
       "rbase": "24812",
       "nome": "CANUDOS SERVICOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24837",
       "numero": "0",
       "estado": "BA",
       "cidade": "Vera Cruz",
       "bairro": "Conceição",
       "complemento": "ADCON ILHA, LADO POUSADA TROPICAL",
       "cep": "44470000",
       "rbase": "24837",
       "nome": "ILHA DE PASARGADA",
       "latitude": -12.925748,
       "longitude": -38.486963,
       "status": "E"
    },
    {
       "id": "24897",
       "numero": "389",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Praia do Flamengo",
       "complemento": "",
       "cep": "41603090",
       "rbase": "24897",
       "nome": "COND MARES DO FLAMENGO",
       "latitude": -12.929781,
       "longitude": -38.323594,
       "status": "E"
    },
    {
       "id": "24899",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "ITABUNA",
       "bairro": "FATIMA",
       "complemento": "",
       "cep": "45.603-445",
       "rbase": "24899",
       "nome": "CASA DA REFRIGERACAO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24900",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "ITABUNA",
       "bairro": "FATIMA",
       "complemento": "",
       "cep": "45603-445",
       "rbase": "24900",
       "nome": "CASA DA REFRIGERACAO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24923",
       "numero": "0",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GRACA",
       "complemento": "",
       "cep": "40.150-130",
       "rbase": "24923",
       "nome": "FLORESTA TROPICAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24924",
       "numero": "263",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GRAÇA",
       "complemento": "Edificio Floresta Tropical",
       "cep": "40150130",
       "rbase": "24924",
       "nome": "FLORESTA TROPICAL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "24988",
       "numero": "65",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Itaigara",
       "complemento": "COND EDF ONASSIS",
       "cep": "41815370",
       "rbase": "24988",
       "nome": "COND EDF ONASSIS",
       "latitude": -12.996886,
       "longitude": -38.462361,
       "status": "E"
    },
    {
       "id": "25157",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARQUE BELA VISTA",
       "complemento": "",
       "cep": "40279-700",
       "rbase": "25157",
       "nome": "ON LINE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25158",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARQUE BELA VISTA",
       "complemento": "",
       "cep": "40279-700",
       "rbase": "25158",
       "nome": "ON LINE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25160",
       "numero": "3244",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "EDF TOMÉ DE SOUZA, SL 1208",
       "cep": "41800700",
       "rbase": "25160",
       "nome": "CONDOMINIO VIVENDAS DA",
       "latitude": -12.996397,
       "longitude": -38.468097,
       "status": "E"
    },
    {
       "id": "25258",
       "numero": "320",
       "estado": "PB",
       "cidade": "Campina Grande",
       "bairro": "Nações",
       "complemento": "",
       "cep": "58402680",
       "rbase": "25258",
       "nome": "CONDOMINIO CAMPO GRANDE",
       "latitude": -7.194154,
       "longitude": -35.879619,
       "status": "E"
    },
    {
       "id": "25579",
       "numero": "KM 2",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Centro",
       "complemento": "S LITORA",
       "cep": "42702400",
       "rbase": "25579",
       "nome": "CONDOMINIO CENTER 5",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25580",
       "numero": "342",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Aracuí",
       "complemento": "",
       "cep": "42702010",
       "rbase": "25580",
       "nome": "CONDOMINIO CENTER 5",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25621",
       "numero": "135",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "",
       "cep": "41830498",
       "rbase": "25621",
       "nome": "BOSQUE DO PARQUE",
       "latitude": -12.999782,
       "longitude": -38.467279,
       "status": "E"
    },
    {
       "id": "25660",
       "numero": "345",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Jiquiá",
       "complemento": "",
       "cep": "50771060",
       "rbase": "25660",
       "nome": "CAEL ENGENHARIA",
       "latitude": -8.08901,
       "longitude": -34.923784,
       "status": "E"
    },
    {
       "id": "25700",
       "numero": "128",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Imbuí",
       "complemento": "Entregar na portaria",
       "cep": "41720420",
       "rbase": "25700",
       "nome": "COND MORADAS BOLANDEIRA",
       "latitude": -12.973222,
       "longitude": -38.435795,
       "status": "E"
    },
    {
       "id": "25708",
       "numero": "3244",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "EDF TOMÉ DE SOUZA, SL 1208",
       "cep": "41800700",
       "rbase": "25708",
       "nome": "BRISAS DO IPITANGA",
       "latitude": -12.996397,
       "longitude": -38.468097,
       "status": "E"
    },
    {
       "id": "25740",
       "numero": "2227",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "EDF SALVADOR PRIME EMPRESARIAL SL 710 TORRE WORK",
       "cep": "41820021",
       "rbase": "25740",
       "nome": "SYENE PARTICIPAÇÕES",
       "latitude": -12.979678,
       "longitude": -38.451385,
       "status": "E"
    },
    {
       "id": "25785",
       "numero": "SN",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ACUPE",
       "complemento": "",
       "cep": "42700-001",
       "rbase": "25785",
       "nome": "CONDOMINIO CENTER 5",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25786",
       "numero": "342",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "ESTRADA DO CÔCO",
       "complemento": "",
       "cep": "42700-001",
       "rbase": "25786",
       "nome": "CONDOMINIO CENTER 5",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "25952",
       "numero": "65",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Valéria",
       "complemento": "1 ANDAR",
       "cep": "41300600",
       "rbase": "25952",
       "nome": "GAMALOG",
       "latitude": -12.874005,
       "longitude": -38.435695,
       "status": "E"
    },
    {
       "id": "26065",
       "numero": "KM 2",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Centro",
       "complemento": "SHOP EST",
       "cep": "42702400",
       "rbase": "26065",
       "nome": "COND. RES. MAR ONDA DAS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26134",
       "numero": "1283",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "SL 802",
       "cep": "41820-021",
       "rbase": "26134",
       "nome": "ALZ TECNOLOGIA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26135",
       "numero": "1283",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ÁRVORES",
       "complemento": "SL 802",
       "cep": "41820-021",
       "rbase": "26135",
       "nome": "ALZ TECNOLOGIA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26190",
       "numero": "KM 2",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Centro",
       "complemento": "S LITORA",
       "cep": "42702400",
       "rbase": "26190",
       "nome": "COND  ESTRELA DO MAR",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26191",
       "numero": "342",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Aracuí",
       "complemento": "",
       "cep": "42702010",
       "rbase": "26191",
       "nome": "COND  ESTRELA DO MAR",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26212",
       "numero": "342",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Aracuí",
       "complemento": "Na rua da loja Mega Insinuante",
       "cep": "42702010",
       "rbase": "26212",
       "nome": "COND. BEIRA RIO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26213",
       "numero": "",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "ESTRADA DO COCO",
       "complemento": "",
       "cep": "42700-001",
       "rbase": "26213",
       "nome": "COND. BEIRA RIO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26283",
       "numero": "324",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "ED HOLDING",
       "cep": "41820022",
       "rbase": "26283",
       "nome": "SMS ESTACIONAMENTOS",
       "latitude": -12.981301,
       "longitude": -38.455795,
       "status": "E"
    },
    {
       "id": "26553",
       "numero": "768",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Rio Vermelho",
       "complemento": "EM FRENTE ESTAÇÃO BAHIA AZUL",
       "cep": "41940060",
       "rbase": "26553",
       "nome": "COND RIO DAS PEDRAS",
       "latitude": -13.005055,
       "longitude": -38.483723,
       "status": "E"
    },
    {
       "id": "26644",
       "numero": "94",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Piatã",
       "complemento": "",
       "cep": "41650700",
       "rbase": "26644",
       "nome": "RES VICTORIA CATHARINA",
       "latitude": -12.949022,
       "longitude": -38.375659,
       "status": "E"
    },
    {
       "id": "26662",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "IAPI",
       "complemento": "GALPÃO",
       "cep": "40330520",
       "rbase": "26662",
       "nome": "PACHECO  FLEX",
       "latitude": -12.957038,
       "longitude": -38.477856,
       "status": "E"
    },
    {
       "id": "26688",
       "numero": "81",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Castelo Branco",
       "complemento": "PROX ANTIGA CLINICA SÃO BERNARDO",
       "cep": "41320100",
       "rbase": "26688",
       "nome": "ENPRO METAL",
       "latitude": -12.907331,
       "longitude": -38.44352,
       "status": "E"
    },
    {
       "id": "26713",
       "numero": "103",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Candeal",
       "complemento": "",
       "cep": "40296320",
       "rbase": "26713",
       "nome": "COND EDF PALAZZO SAVOIA",
       "latitude": -12.994918,
       "longitude": -38.479577,
       "status": "E"
    },
    {
       "id": "26744",
       "numero": "KM 2",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Centro",
       "complemento": "SHOP LIT",
       "cep": "42702400",
       "rbase": "26744",
       "nome": "COND ANTARES RESIDENCE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26745",
       "numero": "342",
       "estado": "BA",
       "cidade": "Lauro de Freitas",
       "bairro": "Aracuí",
       "complemento": "",
       "cep": "42702010",
       "rbase": "26745",
       "nome": "COND ANTARES RESIDENCE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "26829",
       "numero": "2227",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "SSA PRIME TR WORK SL 710",
       "cep": "41820021",
       "rbase": "26829",
       "nome": "CONSTRUTORA GMO",
       "latitude": -12.979678,
       "longitude": -38.451385,
       "status": "E"
    },
    {
       "id": "27066",
       "numero": "1189",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41820-021",
       "rbase": "27066",
       "nome": "Guimaraes Trade",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27067",
       "numero": "1189",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41820-021",
       "rbase": "27067",
       "nome": "Guimaraes Trade",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27068",
       "numero": "KM 0",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "CENTRO",
       "complemento": "SL 204",
       "cep": "42700-001",
       "rbase": "27068",
       "nome": "JM REPRESENTACOES LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27069",
       "numero": "KM 0",
       "estado": "BA",
       "cidade": "LAURO DE FREITAS",
       "bairro": "CENTRO",
       "complemento": "SL 204",
       "cep": "42700-001",
       "rbase": "27069",
       "nome": "JM REPRESENTACOES LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27115",
       "numero": "S/N",
       "estado": "MA",
       "cidade": "São Luís",
       "bairro": "Itaqui",
       "complemento": "BAIA DE SAO MARCOS, ITAQUI",
       "cep": "65085370",
       "rbase": "27115",
       "nome": "COPI",
       "latitude": -2.56221,
       "longitude": -44.336664,
       "status": "E"
    },
    {
       "id": "27196",
       "numero": "2061",
       "estado": "SE",
       "cidade": "Aracaju",
       "bairro": "Inácio Barbosa",
       "complemento": "",
       "cep": "49040840",
       "rbase": "27196",
       "nome": "SETRANSP",
       "latitude": -10.95032,
       "longitude": -37.072009,
       "status": "E"
    },
    {
       "id": "27277",
       "numero": "45",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "COMÉRCIO",
       "complemento": "Sala 410",
       "cep": "40.010-020",
       "rbase": "27277",
       "nome": "CALHEIRA ALMEIDA S A",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27278",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GARCIA",
       "complemento": "",
       "cep": "40100180",
       "rbase": "27278",
       "nome": "CALHEIRA ALMEIDA S A",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27279",
       "numero": "249",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GARCIA",
       "complemento": "A",
       "cep": "40100180",
       "rbase": "27279",
       "nome": "SAMMAR VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27280",
       "numero": "249",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GARCIA",
       "complemento": "A",
       "cep": "40100180",
       "rbase": "27280",
       "nome": "SAMMAR VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27281",
       "numero": "128",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ONDINA",
       "complemento": "",
       "cep": "40170-150",
       "rbase": "27281",
       "nome": "ASSOCIACAO BRAS. DE EDU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27282",
       "numero": "128",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ONDINA",
       "complemento": "",
       "cep": "40170-150",
       "rbase": "27282",
       "nome": "ASSOCIACAO BRAS. DE EDU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27283",
       "numero": "190",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BROTAS",
       "complemento": "",
       "cep": "40.279-901",
       "rbase": "27283",
       "nome": "COND CONVENTION CENTER",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27284",
       "numero": "190",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "BROTAS",
       "complemento": "",
       "cep": "40275430",
       "rbase": "27284",
       "nome": "COND CONVENTION CENTER",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27285",
       "numero": "656",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PITUBA",
       "complemento": "",
       "cep": "41.825-000",
       "rbase": "27285",
       "nome": "CONDOMÍNIO SHOPPING ITA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27286",
       "numero": "656",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": "",
       "cep": "41.825-000",
       "rbase": "27286",
       "nome": "CONDOMÍNIO SHOPPING ITA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27287",
       "numero": "656",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "ITAIGARA",
       "complemento": "",
       "cep": "41.825-000",
       "rbase": "27287",
       "nome": "CONDOMÍNIO SHOPPING ITA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27288",
       "numero": "255",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "LUIS ANSELMO",
       "complemento": "",
       "cep": "40260340",
       "rbase": "27288",
       "nome": "ECLA ENGENHEIROS  CONSU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27289",
       "numero": "255",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "LUIS ANSELMO",
       "complemento": "",
       "cep": "40260340",
       "rbase": "27289",
       "nome": "ECLA ENGENHEIROS  CONSU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27290",
       "numero": "255",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "MATATU",
       "complemento": "",
       "cep": "40.265-020",
       "rbase": "27290",
       "nome": "ECLA ENGENHEIROS  CONSU",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27313",
       "numero": "1543",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "Edf Garcia D’Avila, sobreloja 3",
       "cep": "41820021",
       "rbase": "27313",
       "nome": "P. EXPRESS",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "27339",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Coutos",
       "complemento": "",
       "cep": "40750090",
       "rbase": "27339",
       "nome": "ASSOCIAÇÂO ASMOS",
       "latitude": -12.856417,
       "longitude": -38.476356,
       "status": "E"
    },
    {
       "id": "27340",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Coutos",
       "complemento": "ENTRE A ANTIGA GARAGEM BOA VIAGEM E ESCOLA ANFRÍSIA SANTIAGO",
       "cep": "40750090",
       "rbase": "27340",
       "nome": "ASSOCIAÇÂO ASMOS",
       "latitude": -12.856417,
       "longitude": -38.476356,
       "status": "E"
    },
    {
       "id": "27396",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SIMOES FILHO",
       "bairro": "CIA",
       "complemento": "",
       "cep": "43.700-000",
       "rbase": "27396",
       "nome": "PLAST BEIJA FLOR LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27397",
       "numero": "",
       "estado": "BA",
       "cidade": "SIMOES FILHO",
       "bairro": "CIA",
       "complemento": "",
       "cep": "43.700-000",
       "rbase": "27397",
       "nome": "PLAST BEIJA FLOR LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27398",
       "numero": "74",
       "estado": "BA",
       "cidade": "SANTO ANTONIO DE JESUS",
       "bairro": "ANDAIA",
       "complemento": "",
       "cep": "44572-570",
       "rbase": "27398",
       "nome": "ADIB",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27399",
       "numero": "74",
       "estado": "BA",
       "cidade": "SANTO ANTONIO DE JESUS",
       "bairro": "ANDAIA",
       "complemento": "",
       "cep": "44572-570",
       "rbase": "27399",
       "nome": "ADIB",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27400",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARALELA",
       "complemento": "5 3 AND",
       "cep": "41611-670",
       "rbase": "27400",
       "nome": "ASTECOM",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27401",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PARALELA",
       "complemento": "5 3 AND",
       "cep": "41611-670",
       "rbase": "27401",
       "nome": "ASTECOM",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27402",
       "numero": "3832",
       "estado": "BA",
       "cidade": "CAMAÇARI",
       "bairro": "POLO PETROQUIMICO",
       "complemento": "MONSANTO",
       "cep": "42.810-000",
       "rbase": "27402",
       "nome": "KORDSA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27403",
       "numero": "3832",
       "estado": "BA",
       "cidade": "CAMACARI (NÃO USAR)",
       "bairro": "POLO PETROQUIMICO",
       "complemento": "",
       "cep": "42.810-000",
       "rbase": "27403",
       "nome": "KORDSA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "27417",
       "numero": "126",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "EDF COSTA ANDRADE, SL 306",
       "cep": "41820768",
       "rbase": "27417",
       "nome": "SERVPRED LTDA",
       "latitude": -12.980089,
       "longitude": -38.455582,
       "status": "E"
    },
    {
       "id": "27418",
       "numero": "1822",
       "estado": "CE",
       "cidade": "Fortaleza",
       "bairro": "Dionisio Torres",
       "complemento": "- de 235/236 ao fim",
       "cep": "60135228",
       "rbase": "27418",
       "nome": "SAMEAC",
       "latitude": -3.749812,
       "longitude": -38.510154,
       "status": "E"
    },
    {
       "id": "27432",
       "numero": "620",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "",
       "cep": "41820020",
       "rbase": "27432",
       "nome": "PESSOA E PESSOA ADVOGAD",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "27821",
       "numero": "1672",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "40.000-000",
       "rbase": "27821",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": -12.980559,
       "longitude": -38.464876,
       "status": "E"
    },
    {
       "id": "27924",
       "numero": "1672",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "B. V. DE SAO CAETANO",
       "complemento": "000000000",
       "cep": "00000000",
       "rbase": "27924",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28294",
       "numero": "1550",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "Ed Premier Sala 806/807",
       "cep": "41810012",
       "rbase": "28294",
       "nome": "3P INVESTIMENTOS E PART",
       "latitude": -12.996047,
       "longitude": -38.451196,
       "status": "E"
    },
    {
       "id": "28295",
       "numero": "1550",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "Ed Premier Sala 806/807",
       "cep": "41810012",
       "rbase": "28295",
       "nome": "3P INVESTIMENTOS E PART",
       "latitude": -12.996047,
       "longitude": -38.451196,
       "status": "E"
    },
    {
       "id": "28318",
       "numero": "345",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Jiquiá",
       "complemento": "",
       "cep": "50771060",
       "rbase": "28318",
       "nome": "CAEL ENGENHARIA",
       "latitude": -8.08901,
       "longitude": -34.923784,
       "status": "E"
    },
    {
       "id": "28371",
       "numero": "185B",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GRS RURAIS PR VARGAS",
       "complemento": "GR VARGA",
       "cep": "41230-215",
       "rbase": "28371",
       "nome": "ATLAS PAPELARIA LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28372",
       "numero": "185A",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "GRS RURAIS PR VARGAS",
       "complemento": "",
       "cep": "41230-215",
       "rbase": "28372",
       "nome": "ATLAS PAPELARIA LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28504",
       "numero": "91",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Parque Bela Vista",
       "complemento": "SL203 ED PRADO EMPRES",
       "cep": "40279120",
       "rbase": "28504",
       "nome": "QUALITY",
       "latitude": -12.98903,
       "longitude": -38.472203,
       "status": "E"
    },
    {
       "id": "28792",
       "numero": "123",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Stiep",
       "complemento": "",
       "cep": "41770235",
       "rbase": "28792",
       "nome": "FAC BAIANA DE DIREITO",
       "latitude": -12.983924,
       "longitude": -38.450442,
       "status": "E"
    },
    {
       "id": "28793",
       "numero": "123",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Stiep",
       "complemento": "",
       "cep": "41770235",
       "rbase": "28793",
       "nome": "FAC BAIANA DE DIREITO",
       "latitude": -12.983924,
       "longitude": -38.450442,
       "status": "E"
    },
    {
       "id": "28794",
       "numero": "2771",
       "estado": "BA",
       "cidade": "FEIRA DE SANTANA",
       "bairro": "CAPUCHINHOS",
       "complemento": "",
       "cep": "44.060-000",
       "rbase": "28794",
       "nome": "JUBIABA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28795",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CABULA",
       "complemento": "",
       "cep": "41.150-595",
       "rbase": "28795",
       "nome": "JUBIABA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28806",
       "numero": "849",
       "estado": "BA",
       "cidade": "FEIRA DE SANTANA",
       "bairro": "CENTRO",
       "complemento": "",
       "cep": "44.001-615",
       "rbase": "28806",
       "nome": "NORAUTO VEICULOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28807",
       "numero": "3301",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CABULA VII",
       "complemento": "MORENA VEICULOS",
       "cep": "41.150595",
       "rbase": "28807",
       "nome": "NORAUTO VEICULOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28826",
       "numero": "1601",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cabula VI",
       "complemento": "CENTRO EMP CACHOEIRINHA SL 32 A 35",
       "cep": "41181057",
       "rbase": "28826",
       "nome": "BAHIA SECURITY SEG PRIV",
       "latitude": -12.954598,
       "longitude": -38.436772,
       "status": "E"
    },
    {
       "id": "28826",
       "numero": "1601",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Cabula VI",
       "complemento": "CENTRO EMP CACHOEIRINHA SL 32 A 35",
       "cep": "41181057",
       "rbase": "28826",
       "nome": "BAHIA SECURITY SEGURANC",
       "latitude": -12.954598,
       "longitude": -38.436772,
       "status": "E"
    },
    {
       "id": "28858",
       "numero": "SN",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "MATA ESCURA",
       "complemento": "LOTE 07",
       "cep": "41.230-040",
       "rbase": "28858",
       "nome": "TORRE EMPREENDIMENTOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28859",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "MATA ESCURA",
       "complemento": "",
       "cep": "41.230-040",
       "rbase": "28859",
       "nome": "TORRE EMPREENDIMENTOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28867",
       "numero": "88",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Santo Amaro",
       "complemento": "",
       "cep": "50100260",
       "rbase": "28867",
       "nome": "AFUSPE",
       "latitude": -8.04568,
       "longitude": -34.881556,
       "status": "E"
    },
    {
       "id": "28910",
       "numero": "300",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "NARANDIBA",
       "complemento": "",
       "cep": "41.186-900",
       "rbase": "28910",
       "nome": "COELBA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28911",
       "numero": "300",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "NARANDIBA",
       "complemento": "",
       "cep": "41.186900",
       "rbase": "28911",
       "nome": "COELBA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28920",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "MATA ESCURA",
       "complemento": "LOTE 07",
       "cep": "41290-000",
       "rbase": "28920",
       "nome": "TORRE EMPREENDIMENTOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28921",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "MATA ESCURA",
       "complemento": "LOTE 07",
       "cep": "41290-000",
       "rbase": "28921",
       "nome": "TORRE EMPREENDIMENTOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28959",
       "numero": "2135",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FEDERACAO",
       "complemento": "",
       "cep": "40.000-000",
       "rbase": "28959",
       "nome": "PROMEDICA PROPAT",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "28960",
       "numero": "2135",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "FEDERACAO",
       "complemento": "",
       "cep": "40210000",
       "rbase": "28960",
       "nome": "PROMEDICA PROPAT",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29066",
       "numero": "385",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PORTO SECO PIRAJA",
       "complemento": "QD B",
       "cep": "41.233-010",
       "rbase": "29066",
       "nome": "VEDACIT",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29067",
       "numero": "385",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "PORTO SECO PIRAJA",
       "complemento": "",
       "cep": "41.233-010",
       "rbase": "29067",
       "nome": "VEDACIT",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29075",
       "numero": "3301",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CABULA VII",
       "complemento": "",
       "cep": "41.150-595",
       "rbase": "29075",
       "nome": "MORENA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29076",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "STIEP",
       "complemento": "",
       "cep": "41.150-595",
       "rbase": "29076",
       "nome": "MORENA VEICULOS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29084",
       "numero": "106",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "SL 01 ED. JJB CENTER",
       "cep": "41820665",
       "rbase": "29084",
       "nome": "VIABAHIA CONCESSIONARIA",
       "latitude": -12.988182,
       "longitude": -38.456829,
       "status": "E"
    },
    {
       "id": "29187",
       "numero": "63",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Campinas de Pirajá",
       "complemento": "",
       "cep": "41270000",
       "rbase": "29187",
       "nome": "SETEL CONSTRUTORA",
       "latitude": -12.924891,
       "longitude": -38.467907,
       "status": "E"
    },
    {
       "id": "29187",
       "numero": "63",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Campinas de Pirajá",
       "complemento": "",
       "cep": "41270000",
       "rbase": "29187",
       "nome": "SETEL OBRA 230",
       "latitude": -12.924891,
       "longitude": -38.467907,
       "status": "E"
    },
    {
       "id": "29196",
       "numero": "1815",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Federação",
       "complemento": "Bloco A, Sala 205, 2º andar, Centro Médico e Empresarial - CME",
       "cep": "40210750",
       "rbase": "29196",
       "nome": "PROMEDICA PROPAT",
       "latitude": -12.99259,
       "longitude": -38.507,
       "status": "E"
    },
    {
       "id": "29503",
       "numero": "1672",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41820-020",
       "rbase": "29503",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29504",
       "numero": "1672",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "CAMINHO DAS ARVORES",
       "complemento": "",
       "cep": "41.820-020",
       "rbase": "29504",
       "nome": "NUTRICASH SERVIÇOS LTDA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29518",
       "numero": "269",
       "estado": "BA",
       "cidade": "Itabuna",
       "bairro": "Góes Calmon",
       "complemento": "1º andar",
       "cep": "45605388",
       "rbase": "29518",
       "nome": "BIOFABRICA",
       "latitude": -14.793084,
       "longitude": -39.26612,
       "status": "E"
    },
    {
       "id": "29535",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": "",
       "cep": "41523190",
       "rbase": "29535",
       "nome": "CHESF - SSA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29536",
       "numero": "",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": "",
       "cep": "41523190",
       "rbase": "29536",
       "nome": "CHESF - SSA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29830",
       "numero": "",
       "estado": "PE",
       "cidade": "RECIFE",
       "bairro": "RECIFE ANTIGO",
       "complemento": "",
       "cep": "50030-230",
       "rbase": "29830",
       "nome": "TRF 5 REGIÃO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29831",
       "numero": "",
       "estado": "PE",
       "cidade": "RECIFE",
       "bairro": "RECIFE ANTIGO",
       "complemento": "",
       "cep": "50030-230",
       "rbase": "29831",
       "nome": "TRF 5 REGIÃO",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29840",
       "numero": "",
       "estado": "AL",
       "cidade": "MACEIO",
       "bairro": "BEBEDOURO",
       "complemento": "",
       "cep": "57018-330",
       "rbase": "29840",
       "nome": "SIMA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29841",
       "numero": "",
       "estado": "AL",
       "cidade": "MACEIO",
       "bairro": "BEBEDOURO",
       "complemento": "",
       "cep": "57018-330",
       "rbase": "29841",
       "nome": "SIMA",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29844",
       "numero": "3165",
       "estado": "SE",
       "cidade": "ARACAJU",
       "bairro": "GRAGERU",
       "complemento": "",
       "cep": "49027-010",
       "rbase": "29844",
       "nome": "EMGETIS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29845",
       "numero": "3165",
       "estado": "SE",
       "cidade": "ARACAJU",
       "bairro": "GRAGERU",
       "complemento": "",
       "cep": "49027-010",
       "rbase": "29845",
       "nome": "EMGETIS",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "29901",
       "numero": "3244",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "12 andar, sala 1208",
       "cep": "41800700",
       "rbase": "29901",
       "nome": "CONDOMINIO SANTOS DUMON",
       "latitude": -12.996397,
       "longitude": -38.468097,
       "status": "E"
    },
    {
       "id": "30141",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SIMOES FILHO",
       "bairro": "CENTRO",
       "complemento": "",
       "cep": "43.700-000",
       "rbase": "30141",
       "nome": "REALSI LITORAL NORTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "30142",
       "numero": "901",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "Itacaranha",
       "complemento": "Garagem da Plataforma",
       "cep": "40713580",
       "rbase": "30142",
       "nome": "REALSI LITORAL NORTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "30152",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SIMOES FILHO",
       "bairro": "CENTRO",
       "complemento": "",
       "cep": "43.700-000",
       "rbase": "30152",
       "nome": "REALSI LITORAL NORTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "30153",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "SIMOES FILHO",
       "bairro": "CENTRO",
       "complemento": "",
       "cep": "43.700-000",
       "rbase": "30153",
       "nome": "REALSI LITORAL NORTE",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "30485",
       "numero": "1022",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Imbiribeira",
       "complemento": "- até 1920 - lado par",
       "cep": "51170000",
       "rbase": "30485",
       "nome": "POSTO XINGU LTDA",
       "latitude": -8.099519,
       "longitude": -34.910649,
       "status": "E"
    },
    {
       "id": "31026",
       "numero": "1022",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Imbiribeira",
       "complemento": "POSTO PETROMEGA",
       "cep": "51170000",
       "rbase": "31026",
       "nome": "MASTER POSTO",
       "latitude": -8.099519,
       "longitude": -34.910649,
       "status": "E"
    },
    {
       "id": "32055",
       "numero": "484",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Costa Azul",
       "complemento": "ED DENIS",
       "cep": "41760200",
       "rbase": "32055",
       "nome": "COND. EDF DENIS",
       "latitude": -12.993626,
       "longitude": -38.444314,
       "status": "E"
    },
    {
       "id": "32503",
       "numero": "2152",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "São Marcos",
       "complemento": "SUBSOLO",
       "cep": "41253190",
       "rbase": "32503",
       "nome": "HOSP SAO RAFAEL",
       "latitude": -12.930188,
       "longitude": -38.429387,
       "status": "E"
    },
    {
       "id": "32503",
       "numero": "2152",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "São Marcos",
       "complemento": "SUBSOLO",
       "cep": "41253190",
       "rbase": "32503",
       "nome": "MONTE TABOR",
       "latitude": -12.930188,
       "longitude": -38.429387,
       "status": "E"
    },
    {
       "id": "32503",
       "numero": "2152",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "São Marcos",
       "complemento": "SUBSOLO",
       "cep": "41253190",
       "rbase": "32503",
       "nome": "MONTE TABOR - ULF",
       "latitude": -12.930188,
       "longitude": -38.429387,
       "status": "E"
    },
    {
       "id": "32642",
       "numero": "192",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Aflitos",
       "complemento": "CASA AMARELA",
       "cep": "52050340",
       "rbase": "32642",
       "nome": "CONSERVICE",
       "latitude": -8.041209,
       "longitude": -34.895038,
       "status": "E"
    },
    {
       "id": "32867",
       "numero": "74",
       "estado": "BA",
       "cidade": "SANTO ANTONIO DE JESUS",
       "bairro": "ANDAIA",
       "complemento": "",
       "cep": "44572-570",
       "rbase": "32867",
       "nome": "ADIB",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "32868",
       "numero": "74",
       "estado": "BA",
       "cidade": "SANTO ANTONIO DE JESUS",
       "bairro": "ANDAIA",
       "complemento": "",
       "cep": "44.572-570",
       "rbase": "32868",
       "nome": "ADIB",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "32874",
       "numero": "2464",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Imbuí",
       "complemento": "SHOP IMBUI PLAZA SL 212",
       "cep": "41720040",
       "rbase": "32874",
       "nome": "TERRA BRASILIS",
       "latitude": -12.969028,
       "longitude": -38.434099,
       "status": "E"
    },
    {
       "id": "33641",
       "numero": "1672",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "Edf Catabas Empresarial 4 ANDAR",
       "cep": "41820020",
       "rbase": "33641",
       "nome": "MAP/ SEC. DE SAUDE",
       "latitude": -12.980727,
       "longitude": -38.45613,
       "status": "E"
    },
    {
       "id": "34862",
       "numero": "4362",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "TERM RODOVIARIO",
       "cep": "41800700",
       "rbase": "34862",
       "nome": "SINART TRFS",
       "latitude": -12.996397,
       "longitude": -38.468097,
       "status": "E"
    },
    {
       "id": "34865",
       "numero": "4362",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "TERM RODOVIARIO",
       "cep": "41800700",
       "rbase": "34865",
       "nome": "SINART",
       "latitude": -12.996397,
       "longitude": -38.468097,
       "status": "E"
    },
    {
       "id": "34866",
       "numero": "4362",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Pituba",
       "complemento": "TERM RODOVIARIO",
       "cep": "41800700",
       "rbase": "34866",
       "nome": "SINART VALENÇA",
       "latitude": -12.996397,
       "longitude": -38.468097,
       "status": "E"
    },
    {
       "id": "36270",
       "numero": "2152",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": "",
       "cep": "41.253-190",
       "rbase": "36270",
       "nome": "HOSP SAO RAFAEL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "36271",
       "numero": "2152",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SÃO MARCOS",
       "complemento": "",
       "cep": "41.253190",
       "rbase": "36271",
       "nome": "HOSP SAO RAFAEL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "36283",
       "numero": "2152",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": "",
       "cep": "41.253-190",
       "rbase": "36283",
       "nome": "HOSP SAO RAFAEL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "36284",
       "numero": "2152",
       "estado": "BA",
       "cidade": "SALVADOR",
       "bairro": "SAO MARCOS",
       "complemento": "",
       "cep": "41253-190",
       "rbase": "36284",
       "nome": "HOSP SAO RAFAEL",
       "latitude": 0,
       "longitude": 0,
       "status": "N"
    },
    {
       "id": "36385",
       "numero": "S/N",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Jardim das Margaridas",
       "complemento": "PQ RECREIO DOS BANDEIRANTES QD 12  LT 08/09",
       "cep": "41502385",
       "rbase": "36385",
       "nome": "LC LACROSE",
       "latitude": -12.903758,
       "longitude": -38.35057,
       "status": "E"
    },
    {
       "id": "37367",
       "numero": "1022",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Imbiribeira",
       "complemento": "MEGA POSTO SHELL",
       "cep": "51170000",
       "rbase": "37367",
       "nome": "POSTO MODELO",
       "latitude": -8.091005,
       "longitude": -34.908447,
       "status": "E"
    },
    {
       "id": "37368",
       "numero": "1022",
       "estado": "PE",
       "cidade": "Recife",
       "bairro": "Imbiribeira",
       "complemento": "MEGA POSTO SHELL",
       "cep": "51170000",
       "rbase": "37368",
       "nome": "POSTO TACARUNA",
       "latitude": -8.091005,
       "longitude": -34.908447,
       "status": "E"
    },
    {
       "id": "38700",
       "numero": "314",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "EDF ANTARES",
       "cep": "41820770",
       "rbase": "38700",
       "nome": "CONDOMINIO PARAISO",
       "latitude": -12.979437,
       "longitude": -38.455911,
       "status": "E"
    },
    {
       "id": "40357",
       "numero": "450",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Caminho das Árvores",
       "complemento": "SL 2501 ED SUAREZ",
       "cep": "41820020",
       "rbase": "40357",
       "nome": "NUTRICASH TESTE 1",
       "latitude": -12.975229,
       "longitude": -38.457883,
       "status": "E"
    },
    {
       "id": "41840",
       "numero": "777",
       "estado": "BA",
       "cidade": "Salvador",
       "bairro": "Engomadeira",
       "complemento": "",
       "cep": "41200005",
       "rbase": "41840",
       "nome": "SALAD CREATIONS",
       "latitude": -12.949348,
       "longitude": -38.458019,
       "status": "E"
    }
 ]

}
